### ISSUE TITLE
Translation questions

### ISSUE THREAD

**Issue by thexkey** [Azuriom/Azuriom#100]
hi, i want to translate some languages for Azuriom, but also participate in hacktoberfest but,
from what i see on previous PR's you use a site outside of github for translations.

can i send a PR with the translations anyways?

**Comment by MrMicky-FR** [comment]
Hi, great, which languages you want to translate ?

**Comment by MrMicky-FR** [comment]
The Spanish translation is already done, you can view it [here](https://translate.azuriom.com/project/azuriom/es-ES), but isn’t approved yet. If you want, I can give you the proofreader role on Crowdin (the translations platform) so you can approve the translations.

Also if you want, you can translate [our website](https://github.com/Azuriom/azuriom.com) by directly submitting a pull request with the translations (like [this](https://github.com/Azuriom/azuriom.com/pull/1)).
