### ISSUE TITLE
Error when trying to install at linking steam account

### ISSUE THREAD

**Issue by givinghawk** [Azuriom/Azuriom#102]
An error occurred: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'after `cpu`, `created_at` timestamp null, `updated_at` timestamp null) defaul...' at line 1 (SQL: create table `server_stats` (`id` bigint unsigned not null auto_increment primary key, `server_id` int unsigned not null, `players` int unsigned not null, `ram` int unsigned null, `cpu` decimal(8, 2) unsigned null, `data` text null after `cpu`, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by powerGames1** [comment]
I have the same error with me I tested more tecnic may nothing works

**Comment by MrMicky-FR** [comment]
Hi, I've updated the release, just download the zip again

**Comment by MrMicky-FR** [comment]
If you downloaded from our website, you can just delete the files and restart the installation

**Comment by givinghawk** [comment]
the one on the website does not work for me but the release on github does work on my web server

**Comment by givinghawk** [comment]
i just re downloaded and re started, its fixed

**Comment by MrMicky-FR** [comment]
Fixed in https://github.com/Azuriom/Azuriom/commit/b5f44422d3154e5385d5a2834dac8e5098f03485.
