### ISSUE TITLE
Allow users to access specific pages with maintenance mode enabled

### ISSUE THREAD

**Issue by ElBananaa** [Azuriom/Azuriom#103]
Giving users access to specific pages with maintenance mode enable can pretty pretty useful, as this can allow them to read terms & policies.
I believe this is also required for european websites since website owners need to provide users an access to their cookie policy as soon as you collect any data (which is the case with the `azuriom_session` cookie, even tho maintenance mode is enabled)

**Comment by MrMicky-FR** [comment]
Added in https://github.com/Azuriom/Azuriom/commit/ad14e145d15b4fa0277598a9211c2a64450529b3
