### ISSUE TITLE
Bug concernant la gestion des thèmes

### ISSUE THREAD

**Issue by GeistFighter** [Azuriom/Azuriom#107]
Bonjour,

Je pense avoir trouvé un bug concernant la gestion des thèmes, actuellement j'utilise un thème personnel.

Ce que je remarque lorsque je mets à jour les thèmes que j'avais téléchargé(du market), c'est que la configuration de mon thème actuel saute, et la configuration du thème que je viens de mettre à jour le remplace, notez que le thème(mise à jour) est juste téléchargé, il n'est pas activé.

Je dois donc vider le cache dans les paramètres pour résoudre ce problème et retrouver la configuration de mon thème.

**Comment by MrMicky-FR** [comment]
Merci, c’est corrigé dans le commit https://github.com/Azuriom/Azuriom/commit/c2e5a760913f0aef14609832d7392de9781298ba. La prochaine mise à jour sera publiée très prochainement
