### ISSUE TITLE
Ajouter le support bedrock (prefix)

### ISSUE THREAD

**Issue by amarcais53** [Azuriom/Azuriom#111]
https://github.com/Azuriom/Azuriom/blob/cd2f9267d4781c2e1e41eef811304da3374e0b3d/app/Rules/Username.php#L23
a cette ligne il faudrais modifier le regex par '/^[\.A-Za-z0-9_*]+$/' pour pouvoir permettre aux joueurs bedrock de s'inscrire sur le site car le prefix par defaut avec geyser cest un point et la les points sont interdit dans l'inscription
Sans ca quand les joueurs votent il ne gagnent pas de récompenses car le point est manquant

**Comment by amarcais53** [comment]
petite erreur de typo dans le regex je vouslais dire       '/^[\.A-Za-z0-9_*]+$/'

**Comment by amarcais53** [comment]
bon ca me vire le \ je sais pas pourquoi

**Comment by MrMicky-FR** [comment]
Merci, je vais update ça, c’est que Geyser a modifié le préfixe par défaut il y a quelques mois : https://github.com/GeyserMC/Floodgate/commit/bc0f298e5ca4d1f562286a9501c8d4a9f59e7929

**Comment by Symeloxk** [comment]
Bonjour,
Merci ^^

**Comment by magrigry** [comment]
> Merci, je vais update ça, c’est que Geyser a modifié le préfixe par défaut il y a quelques mois : [GeyserMC/Floodgate@bc0f298](https://github.com/GeyserMC/Floodgate/commit/bc0f298e5ca4d1f562286a9501c8d4a9f59e7929)

Ce serait top si c’était configurable vu qu’on peut changer le prefix par défaut avec Geyser

**Comment by MrMicky-FR** [comment]
Merci c’est ajouté dans le commit https://github.com/Azuriom/Azuriom/commit/c2e5a760913f0aef14609832d7392de9781298ba. La prochaine mise à jour sera publiée très prochainement
