### ISSUE TITLE
Convert two variable assignments to the usage of combined operators

### ISSUE THREAD

**Issue by elfring** [Azuriom/Azuriom#113]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of combined operators](https://www.php.net/manual/en/language.operators.assignment.php#language.operators.assignment.arithmetic "Description for assignment operators") accordingly.

```diff
diff --git a/app/Support/Charts.php b/app/Support/Charts.php
index 3f74fac..2ae6bee 100644
--- a/app/Support/Charts.php
+++ b/app/Support/Charts.php
@@ -51,7 +51,7 @@ class Charts
     {
         $date = $start->clone();
         $dates = collect();
-        $column = $column ?? $query->getModel()->getCreatedAtColumn();
+        $column ??= $query->getModel()->getCreatedAtColumn();
 
         while ($date->isPast() || $date->isToday()) {
             $dates->put($date->format('Y-m-d'), 0);
@@ -100,7 +100,7 @@ class Charts
     {
         $date = $start->clone();
         $dates = collect();
-        $column = $column ?? $query->getModel()->getCreatedAtColumn();
+        $column ??= $query->getModel()->getCreatedAtColumn();
 
         while ($date->isPast()) {
             $dates->put($date->format('Y-m'), 0);
```

**Comment by MrMicky-FR** [comment]
Hello, sorry for the delay, not sure why but didn’t saw this issue earlier.
Thanks for the suggestion, but the null coalescing assignment operator was added in PHP 7.4 so unfortunately we can’t use it yet as currently PHP 7.3 is still supported

**Comment by elfring** [comment]
:thought_balloon: Will the shown change possibilities become applicable with a subsequent version for this CMS software?

**Comment by MrMicky-FR** [comment]
Yes, once we drop PHP 7.3 support

**Comment by elfring** [comment]
Would you like to put such changes into a corresponding waiting queue?

**Comment by MrMicky-FR** [comment]
What do you mean ?

**Comment by elfring** [comment]
:thought_balloon: How do you think about to connect this issue with a milestone (or roadmap)?

**Comment by MrMicky-FR** [comment]
This will be done once we drop PHP 7.3, but we won’t specifically add this to a milestone or a roadmap as it’s a really minor styling change (literally 8 characters on 2 lines)
