### ISSUE TITLE
Error during GMod server link

### ISSUE THREAD

**Issue by XeniumNetwork** [Azuriom/Azuriom#114]
Hello,
since the update of this week on gmod and gmodserver. The rcon access between the server and the cms does not work anymore: `The connection to the server failed: GetInfo: Packet header mismatch. (0x41)`.

Thank you for your help.

**Comment by MrMicky-FR** [comment]
Hi, this will be patched as soon as possible. Until the next update, to fix the issue, you can you can replace the file `vendor/xpaw/php-source-query-class/SourceQuery/SourceQuery.php` with this one : https://gist.github.com/MrMicky-FR/8fe40bbd392cb3e296faef4f203679fb
