### ISSUE TITLE
Add table support in editor

### ISSUE THREAD

**Issue by Erdack54** [Azuriom/Azuriom#118]
Hello, first of all thank you for your work Azuriom is incredible, I thought that the possibility of making charts (Table) would be perfect

![Exemple](http://www.image-heberg.fr/files/1643638055178672590.png)

**Comment by MrMicky-FR** [comment]
Added in https://github.com/Azuriom/Azuriom/commit/aa24cd7514e0673cdeb7363ada25ba8c4f233179, it will be available in the next Azuriom update

**Comment by Erdack54** [comment]
That's awesome! Sorry to reopen the issue for this, but do you have an idea how soon the next update will be published? Once again thank you for your amazing work 🙂

**Comment by MrMicky-FR** [comment]
Hi, it should be in one or two week 😃

**Comment by Erdack54** [comment]
Thank you for your reply 👍, have a nice day
