### ISSUE TITLE
Jirai bug

### ISSUE THREAD

**Issue by SharkZekrom** [Azuriom/Azuriom#124]
j'ai cette erreur lorsque je veux activer jirai avec la dernière version de azuriom
 
 Ce plugin n'est pas compatible avec votre version d'Azuriom.

**Comment by MrMicky-FR** [comment]
Il faudrait signaler ce problème sur le repo GitHub du plugin concerné (https://github.com/magrigry/jirai/) étant donné que le problème ne vient pas d’Azuriom
