### ISSUE TITLE
Add more than one server in the house.

### ISSUE THREAD

**Issue by Stewart-Anubis** [Azuriom/Azuriom#129]
You can add more than one server on the home screen and not just the default.
A table with servers registered online and players.

**Comment by Oximov** [comment]
For me display all server inside the main page is useless. But if you want you can create a plugin who display a box or modal with status of all server.

**Comment by MrMicky-FR** [comment]
This has already been added in version 1.0 few days ago, it will be available when the v1.0 is released 😃
