### ISSUE TITLE
Post forum not formatted when edit

### ISSUE THREAD

**Issue by Elikill58** [Azuriom/Azuriom#130]
I'm using Forum's plugin version 0.1.25, with Azurium 0.5.0 (and now with 0.5.1).

I can't format post with BBCode or markdown. On the forum's parameters, I will set it.

It seems to work when I create the post, but when I edit it:
During edit:
![image](https://user-images.githubusercontent.com/17381066/156855480-837d14d0-c9de-4a67-8a5f-f95b1f4d3e16.png)
After saving:
![image](https://user-images.githubusercontent.com/17381066/156855491-7b8c54d0-dc7b-400a-9d5d-8bfd54241d4e.png)

The editor is different from posting:
![image](https://user-images.githubusercontent.com/17381066/156855582-2d28d8cc-a895-4d5f-bc93-5e6572fb035f.png)
Then from editing:
![image](https://user-images.githubusercontent.com/17381066/156855597-7320c699-6e41-47a5-91a8-015bd0ed537c.png)

I think that it come from that but I don't know why exactly.

How can I fix it ?

**Comment by MrMicky-FR** [comment]
Hi, please use our Discord for support about plugin, as this GitHub repo is for issues related to Azuriom itself. Also try to disable your theme and see if you still have this issue

**Comment by Elikill58** [comment]
I already send message on discord but I didn't received any answer, that's why I'm here.

I also searched for a repository of the forum plugin, but I didn't find it. For the theme, I will try.
