### ISSUE TITLE
Bug dans l'onglet "Navbar"

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/Azuriom#134]
Bonjour,

Version; Azuriom V1.0
J'ai trouvé un bug dans l'onglet Navbar, explication :

Quand on clique sur le bouton pour supprimer une navbar, il y a la [popup](https://cdn.discordapp.com/attachments/954499095450492949/956242131754831912/unknown.png) qui demande de confirmer si on veut bien supprimer ce dernier, et le bug est le fait que quand on clique sur "Annuler" il ne ce passe rien.

C'est vraiment un bug léger et minime, mais je tenais à prévenir !

**Comment by Oximov** [comment]
Le bug à été fix et sera dans la prochaine maj
https://github.com/Azuriom/Azuriom/commit/f1754faa346675fcddba71e64e219f90faa0e9c6
