### ISSUE TITLE
Add option to force installation when requirements aren’t satisfied 

### ISSUE THREAD

**Issue by amongfr** [Azuriom/Azuriom#135]
bonjour, je demande d'ajouter un bouton qui permet de forcer l'installation en cas de problème. (ex .incompatible problème d'herbergeur ect )

**Comment by Oximov** [comment]
Hey, ça serrait inutile d'ajouter ce boutons par ce que si l'hébergeur est incompatible ça ne marchera pas (fonction manquate ou autres), et pour les même raison je pense que MrMicky répondra pareil

**Comment by MrMicky-FR** [comment]
Je suis de l’avis d’@Oximov, même si je curieux de connaître l’objectif de ce bouton. Car les pré-requis ne sont pas là juste pour embêter les gens pendant l’installation, si un des pré-requis n’est pas satisfait, il est à peu près sûr que le site ne fonctionnera pas correctement ou pas du tout

**Comment by MrMicky-FR** [comment]
Je ferme l’issue, mais ça n’empêche pas de répondre, et peut être de la ré-ouvrir si besoin
