### ISSUE TITLE
Add option to force more requirements in password validation 

### ISSUE THREAD

**Issue by AliHaine** [Azuriom/Azuriom#136]
Il faudrait ajouter une option avec des pré-requis pour les mots de passe (minimum X caractères, 1 MAJ, 1 caractère spécial, 1 chiffre minimum)

**Comment by MrMicky-FR** [comment]
De mon coté, je ne suis pas très fan d’imposer ce genre de pré-requis (majuscules, miniscules, caractères spéciaux) pour les mots de passes car cela ne les rend pas forcément plus sécurisé. Par exemple `Passw0rd@` n’est pas du tout un mot de passe sécurisé alors qu’il a bien majuscule/minuscule/chiffre/caractère spécial alors qu’une phrase du type `ceci est un mot de passe seulement en minuscule mais beaucoup plus dur a trouver` est très nettement plus dur à trouver alors qu’il y a que des minuscules

**Comment by MrMicky-FR** [comment]
Une image résume bien tout ça ici : https://www.quora.com/Why-do-most-websites-require-such-complicated-passwords-Wouldn-t-a-longer-but-less-complex-password-be-more-secure

**Comment by AliHaine** [comment]
Je comprend ton point de vu cependant je ne suis pas d'accord, je fais des serveurs depuis des années le problème est que des BDD serveur hack ça arrive quasi chaque mois et les joueurs mettent toujours les mêmes mots de passe partout même si leurs MDP ont leak, mot de passe qui sont souvent de type "prenom+pseudo" ou "321456" ou "123prenom" autrement dit des mots de passent très simple et facilement décryptable (sauf dans le cas de Az). Il faudrait juste ajouter l'option et ceux qui veulent imposer des prérequis n'ont qu'à le faire (comme moi). On n'a jamais trop de sécurité :-)
