### ISSUE TITLE
Bug maj

### ISSUE THREAD

**Issue by AliHaine** [Azuriom/Azuriom#138]
Après avoir fait la dernière màj tous les articles (les news) ont été supprimés sans raison, de plus la mise à jour a update tous les fichiers du CMS alors que la màj ne touche que certains fichiers, ça pose un gros problème puisque Az est open source donc les gens font quelques modifs de leurs côtés en fonction de leurs besoins (comme moi) et toutes les modifs que j'effectue sont supprimés après une màj alors que la màj ne touche pas les fichiers que j'avais modifs. En gros un utilisateur ne peut jamais faire de màj s'il modif certains codes lui-même

**Comment by MrMicky-FR** [comment]
Concernant le problème des articles supprimé avec la mise à jour je vais regarder ça.

Pour la partie des fichiers modifiés avec la mise à jour, c’est voulu car si certains fichiers sont modifiés et que seulement une partie est remplacée c’est des erreurs garanties.
Imaginons un cas simple, un site ajoute une méthode `foo()` dans la classe `User` et cette méthode est utilisée dans le fichier `UserController`. Si jamais le fichier `User` est modifié sur GitHub et que la mise à jour change seulement le fichier `User` et pas `UserController`, c’est une erreur garantie dans le fichier `UserController` comme la méthode `User::foo()` n’existera plus.

Pour les modifications, le plus adapté est de si possible faire les modifications avec un thème et des plugins. Et si ces modifications ne sont pas possible avec des plugins (ce qui généralement est très rare), il faudrait maintenir un fork privé du projet pour merge les modifications au fil des maj (pour donner un exemple connu, c’est par exemple ce que fait PaperMC avec Spigot)

**Comment by MrMicky-FR** [comment]
Aussi je le précise au cas où, mais si les changements peuvent bénéficier à tout le monde il ne faut pas hésiter à contribuer en retour au projet via les pulls requests sur GitHub, c’est la force de l’open source 😀
