### ISSUE TITLE
Bug 2FA

### ISSUE THREAD

**Issue by AliHaine** [Azuriom/Azuriom#139]
Quand un utilisateur active la 2FA il est impossible de la désactiver (ça envoie l'erreur confirmer votre mot de passe sans demander le mot de passe)

**Comment by MrMicky-FR** [comment]
Il faudrait plus de détails car de mon coté l’A2F peut être activée/désactivée sans problème. Egalement il faudrait tester sans le thème, et si le problème est résolu en désactivant le thème, cela peut être signalé au développeur du thème.

**Comment by AliHaine** [comment]
Je possède le thème Rainbow je t'avoue que je ne peux pas essayer moi-même, je suis simplement connecté et quand je clic sur activer la 2FA j'ai l'erreur 500 "confirmer votre mot de passe"  https://prnt.sc/mTD5BGNeA4sd

**Comment by MrMicky-FR** [comment]
Après avoir testé le problème provient effectivement du thème. Il suffit de mettre à jour le thème vers la dernière version (2.1.9) pour corriger le problème
