### ISSUE TITLE
Hide SMTP password in admin panel

### ISSUE THREAD

**Issue by AliHaine** [Azuriom/Azuriom#141]
Dans les paramètres mail, on peut cliquer pour voir le mot de passe du mail en clair, ça permet a n'importe qui ayant le panel admin (autorisé ou non, via un hack ou un admin n'ayant pas fait attention au MDP etc) de voir le mot de passe du compte mail en clair, la fonctionnalité n'a pas d'intérêt et peut poser des problèmes de sécurités inutilement

**Comment by MrMicky-FR** [comment]
Si quelqu'un de mal intentionné parvient à avoir accès au panel admin je pense vraiment que noter le mot de passe SMTP sera la dernière chose à faire, d'où l'importance de bien sécuriser les comptes ayants accès au panel admin et de bien gérer les permissions.
Mais effectivement laisser le mot de passe ne sert pas à grand chose, je vais modifier ça pour la prochaine MAJ.

**Comment by MaximeMichaud** [comment]
> Si quelqu'un de mal intentionné parvient à avoir accès au panel admin je pense vraiment que noter le mot de passe SMTP sera la dernière chose à faire, d'où l'importance de bien sécuriser les comptes ayants accès au panel admin et de bien gérer les permissions. Mais effectivement laisser le mot de passe ne sert pas à grand chose, je vais modifier ça pour la prochaine MAJ.

Tous les password dans le panel devraient être cachés. C'est juste une règle générale connue.
À ce point si la personne ne s'en rappelle plus, tant pis pour elle, ou elle peut faire comme moi et aller à la source soit la database.
