### ISSUE TITLE
Add multiples conditions links on register

### ISSUE THREAD

**Issue by AliHaine** [Azuriom/Azuriom#142]
Quand un utilisateur s'inscrit on ne peut que faire accepter les conditions d'utilisation hors la plupart des sites Az ont une boutique, il est nécessaire de faire aussi accepter les conditions générales de ventes.

D'ailleurs quand l'utilisateur clic sur créditer il serait aussi sympathique de pouvoir (si on veut) faire apparaitre une pop-up (a chaque fois) (avec le texte qu'on veut écrire) et une case a cocher pour qu'il confirme qu'il a bien compris le texte de la pop-up (on peut imaginer tout et n'importe quoi, un rappel concernant les litiges etc..) puis une fois la case cocher et que l'utilisateur a cliqué sur continuer alors il est dirigé normalement vers les moyens de paiements

**Comment by vassilidev** [comment]
CGU & CGV à l'inscription, check des CGV pour les utilisateurs déjà inscrits et c'est ok? Le popup à chaque achat ca fait bcp je trouve.

Soit la version en haut soit CGU à l'inscription et CGV a chaque achat + text ?

**Comment by MrMicky-FR** [comment]
@vassilidev Il ne faudrait juste pas que ça soit pensé en terme de CGU/CGV mais de façon configurable, car Azuriom est utilisé dans de nombreux pays ou les différentes conditions peuvent être différentes, et même en France certains sites pourraient avoir envie de rajouter une case à propos du RGPD ou de leur politique de confidentialité par exemple

**Comment by vassilidev** [comment]
Et comment tu ferais ça ?

Quelle approche ?
