### ISSUE TITLE
Bug with Microsoft

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/Azuriom#146]
**FR :**

Bonjour,

J'ai découvert 2 bugs sur mon site (Azuriom V1.0.2 qui utilise les connexions Microosft),

1. Lorsque le mode de Maintenance est activé sur le site, les utilisateurs peuvent tout-de-même "s'inscrire" avec, ce n'est pas reservé à uniquement certaines personnnes.
Mais je pense que ce serait compliquer de régler ce problème, sauf si mon bug N°2 est résolu.

2. A chaque fois que j'éteins mon Ordinateur, je suis déconnecté de mon site.

**EN :**
Hello,

I discovered 2 bugs on my site (Azuriom V1.0.2 which uses Microosft connections),

1. When the maintenance mode is activated on the site, users can still "register" with it, it's not reserved to only some people.
But I think it would be complicated to fix this problem, unless my bug 2nd is solved.

2. Every time I turn off my Computer, I am disconnected from my site.

**Comment by MrMicky-FR** [comment]
Pour le problème n°1 l’inscription n’est pas vraiment séparée de la connexion (d’ailleurs il y a un seul bouton connexion pour les deux)
Pour le problème n°2, il faut cocher l’option sur Microsoft pour rester connecter lors de la connexion
