### ISSUE TITLE
Add diff in action logs

### ISSUE THREAD

**Issue by AliHaine** [Azuriom/Azuriom#147]
Le but des logs c'est d'avoir des informations sur une situation, sur ce qu'il a pu se passer etc. Et il y a un problème avec les màj utilisateur : "Mise à jour de l'utilisateur #227", d'accord mais quoi ? la money, le mail, le mot de passe.. Je pense qu'un peu plus d'infos serait parfait. Sur la droite dans la catégorie paiement y'a un petit œil avec des infos en plus https://prnt.sc/U1UeWHcrpP9x concernant les utilisateurs vous pourriez mettre la même fonctionnalité qui montre un avant/après des modifications

**Comment by vassilidev** [comment]
https://github.com/Azuriom/Azuriom/pull/294
