### ISSUE TITLE
Adding a premium subscription

### ISSUE THREAD

**Issue by skatoux** [Azuriom/Azuriom#149]
First of all, you should know that Azuriom is a very good CMS, congratulations for your work.

I think the arrival of a premium subscription would be a good idea for those who have the means / the desire. The premium subscription could give us access to additional customization, the removal of Azuriom mentions on the site, access to promotions on the extension store, and more... (Why not)

I think it could also allow you to avoid being cheated when people remove the tag directly in the source code.
And above all, it could allow you to run your servers without having to ask for donations or support, it's give and take!

Thank you for reading,
Sincerely,

**Comment by MrMicky-FR** [comment]
Hi,

Thank you for your suggestion, however we don’t plan to add such subscription, as we truly believe in open-source and want to keep Azuriom itself always 100% free and open-source.

Also, the GPL v3 license used by Azuriom prevents us from doing such thing, as the code contains contributions which are also licensed under the GPL v3 license. The license forces Azuriom to always be distributed with the same license, so any premium subscription should also be open-source and it would be possible for anyone to use this premium subscription without paying, so I don’t think it’s make sense. On the same note, removing the copyright would also be some sort of violation to the GPL license.

I hope you understand our decision 😃
