### ISSUE TITLE
Looking for a plugin for Cookiebot

### ISSUE THREAD

**Issue by PManuel1986** [Azuriom/Azuriom#155]
Looking for a plugin for cookiebot as it is mandatory in the EU

**Comment by MrMicky-FR** [comment]
Azuriom itself only use strictly required cookies (session cookie, remember cookie and XSRF cookieà, which doesn’t require any consentement, see https://gdpr.eu/cookies/

If however you decide to include third-party service that uses tracking cookies, you can easily add a JavaScript cookie banner on your website (see settings -> seo in the admin panel to add JS on the pages)
