### ISSUE TITLE
shop

### ISSUE THREAD

**Issue by auraalex21** [Azuriom/Azuriom#157]
Give the possibility to pay directly with paypal or other if you need to go through corners

**Comment by Javdu10** [comment]
@auraalex21 It’s available in the shop plugin. What does « need to go through corners » means though?

**Comment by auraalex21** [comment]
need to go through coins *

**Comment by auraalex21** [comment]
@Javdu10

**Comment by Javdu10** [comment]
@auraalex21 all of that is already possible, please take a little bit more time to explore the Shop plugin, specially the option "use website currency" (which you can tick off) in the Shop plugin settings

**Comment by auraalex21** [comment]
@Javdu10 You don't understand what I want to tell you, can you spend 2 minutes on discord for a clearer explanation?

**Comment by Javdu10** [comment]
Sure hope in discord 👍 

You cannot use direct FIAT currency payments and the website points. You have to choose only one

**Comment by auraalex21** [comment]
@Javdu10 my discord auraalex21#0001

**Comment by MrMicky-FR** [comment]
Hi, please give more details in the issue, because if everyone needs to contact you in Discord to understand what you mean it’s not really practical. Also issues for the shop plugin should be in the Plugin-Shop repo

**Comment by auraalex21** [comment]
ya pas moyen de parler fr ?
