### ISSUE TITLE
Add delete account button in user profile

### ISSUE THREAD

**Issue by SiriHackYT** [Azuriom/Azuriom#160]
Ajouter un bouton pour pouvoir supprimer son compte Azuriom une fois connecté
(ça fera gagné du temps à tout le monde)

**Comment by MrMicky-FR** [comment]
Effectivement ça pourrait être pratique, mais ça ne risque pas de compliquer la gestion des litiges PayPal si le compte a été supprimé ? Ou même par exemple si un utilisateur envoie plein de messages via le support ou le forum, ou des messages à caractères raciste,sexiste etc, puis supprime son compte, il n'y aura plus de moyen de l'identifier

**Comment by SiriHackYT** [comment]
La gestion de litige paypal se fait dans tous les cas avec l'email paypal et pas avec le compte je trouve, mais c'est vrai que les messages utilisateurs avec le support ou le forum peut être plus compliqué
Soit le compte se supprime dans les 30 prochains jours et les messages / demande s'affiche avec un pseudo barré avant de totalement disparaitre 30 jours après
