### ISSUE TITLE
Add a verification system for the legality of the store

### ISSUE THREAD

**Issue by MathisAudureau** [Azuriom/Azuriom#161]
My issue is to request the addition of a new parameter on the shop, it would add a siret, which would then be validated by an API (e.g. the government). If the siret is valid, the user can use the store plugin. 
Or if the user does not have a siret, he can choose to give his funds to AZURIOM.

**Comment by CrazyOutOff** [comment]
Yeah that should be so cool. Like he would give 70% 80% of the benefits he does directly to Azuriom

**Comment by SwartZCoding** [comment]
> My issue is to request the addition of a new parameter on the shop, it would add a siret, which would then be validated by an API (e.g. the government). If the siret is valid, the user can use the store plugin. Or if the user does not have a siret, he can choose to give his funds to AZURIOM.

J'ai jamais vu une connerie pareil.

**Comment by Akira13345** [comment]
> My issue is to request the addition of a new parameter on the shop, it would add a siret, which would then be validated by an API (e.g. the government). If the siret is valid, the user can use the store plugin. Or if the user does not have a siret, he can choose to give his funds to AZURIOM.

Suggestion dénuée d'intérêt et débile, à l'image d'un enfant de 14 ans

**Comment by PandaGuerrier** [comment]
C'est totalement debile, aucun serveur / service minecraft se déclare, et tu n'es pas le premier à être déclaré 🧐

**Comment by SwartZCoding** [comment]
> C'est totalement debile, aucun serveur / service minecraft se déclare, et tu n'es pas le premier à être déclaré 🧐

Je corrige : Aucun serveur "poubelle" se déclare. Nuance :)

**Comment by MathisAudureau** [comment]
@SwartZCoding 
@Akira13345

**Comment by MathisAudureau** [comment]
@SwartZCoding & @Akira13345 If you take the time to respond to this request, I remind you that a critique admits arguments.

**Comment by NathaelB** [comment]
Le problème de ta suggestion est sur la vérification du siret. Comment fais-tu pour vérifier si cette personne est bien l'heureux propriétaire de ce siret ? 

Cela pose un autre problème majeur, qui est sur la sécurité des données transmise (carte d'identité, email, identité numérique) comment tu les stocks et comment tu les sécurise ?

Au vu du public que vise Azurium je ne vois aucun intérêt à établir cette fonctionnalité.

**Comment by Akira13345** [comment]
> @SwartZCoding & @Akira13345 If you take the time to respond to this request, I remind you that a critique admits arguments.

Notre amis le roux à tout dit, je rajoute imagine le SIRET est pas français ?

**Comment by MrMicky-FR** [comment]
Azuriom is an open-source project, it’s not our responsibility to ensure the legality of websites using this project. If you believe a website has this kind of issue, I guess you should contact the fraud or taxes management authorities from the website country about this. 

Also, as Azuriom is open-source, any sort of verification could be easily  remove so it doesn’t make sense to add them.

Finally, while it’s perfectly fine to not agree with a suggestion, as stated in out code of conduct, all conversations should be respectful of differing viewpoints.
