### ISSUE TITLE
Non-game mode

### ISSUE THREAD

**Issue by MaximusMcfly** [Azuriom/Azuriom#163]
Because Azuriom is a great cms, we want to use it for other than gaming, would be great to add a non-game mode

**Comment by MrMicky-FR** [comment]
Hi, this is not planned as Azuriom is a game CMS, and there is a tons of general purpose non-game CMS that would be more suitable for other usages as everything in Azuriom is tailored for games (Azuriom itself, themes, plugins, etc)
