### ISSUE TITLE
Discord ??

### ISSUE THREAD

**Issue by Dreadox** [Azuriom/Azuriom#164]
I cant find your official discord server.. Can i get it here please? Or atleast, someone who can help me to install it ? I get some errors, and i do not know how to fix them..

**Comment by Oximov** [comment]
Here is the link of the discord server : https://azuriom.com/discord

**Comment by MrMicky-FR** [comment]
Please search at least one minute before opening an issue, the Discord link is almost everywhere:
* On the GitHub repository:
  * Discord badge in the third line of the README
  * Community section in the README
* On our website:
  * Discord icon in the navbar
  * Big Discord icon on the homepage
  * Discord link in the footer
* On the dashboard of Azuriom powered websites, in the support button at the top
