### ISSUE TITLE
Other game - Cannot create admin account

### ISSUE THREAD

**Issue by skatoux** [Azuriom/Azuriom#165]
Hello,

I am opening this issue to let you know about a problem.
When we install Azuriom for an "Other game", we don't have the possibility to create an Administrator account. So I find myself on an Azuriom site, without the possibility to go to the administrator panel.

Have a nice day,

**Comment by SharkZekrom** [comment]
Hi use 

php artisan user:create --admin

**Comment by skatoux** [comment]
Hello,

How will a php command create a user in the Azuriom database?
To repeat, when installing Azuriom (in the browser), if we choose the "Other game" option, the CMS itself does not propose to create a "Super-user". That's my problem.

Thanks anyway

**Comment by SharkZekrom** [comment]
you can't use php command in database you will use a ssh console

Azuriom Other game is used for plugins/theme developpment only

**Comment by skatoux** [comment]
Yes, but that's not the point. I'm not trying to create a user on Azuriom with my console or with anything. I'm just saying that the CMS does not propose to do this on installation step.

I didn't know that "Other game" was used only for tests? Is it noted somewhere I can look? How to use Azuriom for other games then? For a community website for example? Does one of the games in the list propose a simple system without using an external connection (Microsoft, steam, ...) or without Minecraft skin on profile page ?

Thanks in advance.

**Comment by SharkZekrom** [comment]
Azuriom offers several games like Minecraft Java, Minecraft Bedrock, Steam games 

you have a Minecraft server ?

**Comment by MrMicky-FR** [comment]
Hi,
The "Other game" option should be used only when developing/using a custom game plugin. We will certainly remove it from the list to prevent any confusion.

About using Azuriom for other game, it would requires to create a small plugin to add a new game (to handle game server link, avatars, etc). The documentation isn't ready yet but a preview is available here: https://deploy-preview-24--azuriom.netlify.app/en/docs/add-new-game

**Comment by MrMicky-FR** [comment]
Fixed with #169
