### ISSUE TITLE
Script Migration

### ISSUE THREAD

**Issue by Walabise** [Azuriom/Azuriom#175]
Bonjour,

Je n'arrive pas à migré mes utilisateurs MineWeb vers Azuriom. Aucun message d'erreur concernant le script. 
Avez vous une idée ou même une mise à jour à t'elle était effectuée concernant le script.
Je suis à la version antérieur de la version 1 d'Azuriom

**Comment by MrMicky-FR** [comment]
Le script de migration n'est plus supporté pour le moment, il sera peut être mis à jour dans le futur
