### ISSUE TITLE
Mail Settings: Apply an error if user does not have email set on profile

### ISSUE THREAD

**Issue by 0xBitMC** [Azuriom/Azuriom#178]
Greetings,

When setting up the mail settings at `admin/settings/mail`, if your profile does not have an email set, the website will display "The test mail has been successfully sent." despite no email or attempt actually being made. 

Suggestion would be to add an error that warns the user that they have no email set on their profile and can't send a test email.

Thanks.

**Comment by MrMicky-FR** [comment]
Added in 145350faad75faabef75f2fa050b2ae9869feb00 :)
