### ISSUE TITLE
Suggestion: Sign-up with Google

### ISSUE THREAD

**Issue by PLRpower** [Azuriom/Azuriom#185]
**Suggestion:** Add a registration option on the `/user/register` page, which allows registration via Google. 
This would retrieve the user's information while simplifying registration with the automatic filling of the fields (Username, email, and password.

[Click here to see an example image](https://user-images.githubusercontent.com/66971495/181904518-3736c5c3-5704-4737-9773-fa3d7276f666.png)

Here is their api, it is very easy to use and very complete: [API Google Sign-in](https://developers.google.com/identity/sign-in/web/sign-in)

**Comment by MrMicky-FR** [comment]
Hi, thanks for your suggestion, however this isn't planned for now as we are planning to create deeper integration between Azuriom and the game servers, which mean we need to login the user through the game account (Steam, Microsoft, etc)
