### ISSUE TITLE
[Suggestion] Group all permissions per plugin

### ISSUE THREAD

**Issue by Elikill58** [Azuriom/Azuriom#186]
I propose to separe permissions per plugin instead of all at same place. This is mostly to be able to make differencies between 2 "Edit configuration" and don't search for the plugin.

This will make able to easier add all permissions of a plugin with a possible top-left checkbox.

Maybe don't create complete div if plugin has only one permission but just put in general area/"all plugins" one

Do like this:

![image](https://user-images.githubusercontent.com/17381066/182093051-cfa9fdd7-f2e4-411f-88da-790658284781.png)

Instead of like this:

![image](https://user-images.githubusercontent.com/17381066/182093107-8651085f-7d04-4566-80e8-43b58c75b96f.png)

**Comment by MrMicky-FR** [comment]
Hi, thanks for the suggestion, unfortunately this isn't possible without breaking changes for plugins, as Azuriom doesn't track which plugin register each permission 😐

> This is mostly to be able to make differences between 2 "Edit configuration" and don't search for the plugin.

In this case the best option would be to contact the plugin author se he can add a more descriptive permission, like "Edit <plugin> configuration"

**Comment by Elikill58** [comment]
Thanks for reply. And is it possible to know with translations key ? Specially with the prefix ? It's not so much well but it should works ?
