### ISSUE TITLE
Update save button icon

### ISSUE THREAD

**Issue by Doncellup** [Azuriom/Azuriom#188]
### Description of your suggestion

Bonjour,
Je propose de remplacer le logo du bouton sauvegarder (qui actuellement ne ressemble à rien…) par celui-ci : https://icons.getbootstrap.com/icons/check2-circle/
![image](https://user-images.githubusercontent.com/90469321/182397761-fdf6eaea-265c-4caa-863d-4a5eee750277.png)

C'est certes un petit changement (donc rapide à intégrer) mais qui améliore grandement l'UX. 
Merci d'avance,
Doncellup

### Advantages

Pour les yeux de tous les admins d'Azuriom. Merci.

**Comment by MrMicky-FR** [comment]
Selon moi l'icône donnée correspond plutôt à "Valider"/"Accepter" que "Enregistrer"/"Sauvegarder".

Concernant la modification de l'icône de sauvegarde, pour le moment celle actuelle me semble être la plus adaptée. C'est également un sujet enflammé sur le GitHub de Bootstrap Icons (https://github.com/twbs/icons/issues/966 🔥), mais si jamais une nouvelle icône de sauvegarde est ajouté dans Bootstrap Icons on pourra voir à ce moment là pour l'utiliser :)

**Comment by Doncellup** [comment]
Oui je comprends pourquoi, l'icone actuel ne représente pas vraiment "Enregistrer". Ils faudrait une disquette, comme sur tous les logiciels :D

**Comment by MrMicky-FR** [comment]
Effectivement beaucoup de personnes sont du même avis comme on peut le voir sur l'issue mentionnée au dessus
