### ISSUE TITLE
Skin incorrect après l'activation de Minecraft premium

### ISSUE THREAD

**Issue by tutur1004** [Azuriom/Azuriom#19]
Hello,

Sur les profiles, toutes les photos pointent vers `https://crafatar.com/avatars/c06f8906-4c8a-4911-9c29-ea1dbd1aab82?size=64&overlay&default=MHF_Steve` Sans prendre en compte l'UUID spécifique du joueur.

**Comment by MrMicky-FR** [comment]
L'UUID par défaut est utilisé lorsque le joueur ne possède pas d'UUID. Ce problème apparaît lorsque la vérification du pseudo avec Mojang est activée après que certains utilisateurs se soient inscrits

**Comment by tutur1004** [comment]
En l'occurrence : 
![image](https://user-images.githubusercontent.com/22873569/83010495-a2403e80-a018-11ea-92fc-91b4f19fa642.png)
https://mcuuid.net/?q=MileKat
Name History | MileKat changed as of 27th Apr, 2017

ça fait longtemps que mon pseudo est MileKat, et il n'est pas reconnu !

**Comment by SkyWarZzeur** [comment]
C'est normal, l'UUID par défaut est utilisé lorsque le joueur ne possède pas d'UUID, en gros pour faire plus simple, cet utilisateur c'est inscrit avant l'activation du paramètre **"Activer la vérification du nom d'utilisateur Minecraft avec minecraft.net"**.
Ducoup cet utilisateur ne possède pas d'uuid sur le site.

**Comment by tutur1004** [comment]
Et comment fix ce truc ?

**Comment by MrMicky-FR** [comment]
Merci, ca sera corrigé dans la prochaine mise à jour.
