### ISSUE TITLE
Use Bootstrap Icons in a page

### ISSUE THREAD

**Issue by Doncellup** [Azuriom/Azuriom#194]
Ca serait bien de pouvoir utiliser des icônes bootstrap dans l'éditeur de texte d'une page (tinymce). 

Si c'est possible ça serait top de pouvoir faire par exemple `[bi-arrows-fullscreen]` pour avoir une icône (comme dans le thème révolution de sloyni pour les boutons de la navbar).

Merci d'avance !

**Comment by MrMicky-FR** [comment]
Added in #195
