### ISSUE TITLE
Suggestion : adding optional icon in the navigation bar

### ISSUE THREAD

**Issue by PLRpower** [Azuriom/Azuriom#199]
### Description of your suggestion

_Hello, here is a suggestion for improvement!_
In the Azuriom admin panel, it would be nice to be able to add optionals icons (bootstrap or fontawesome icons) to the navigation bar elements, with the option to put them before or after the text of the link.

### Advantages

This would allow to simply customize the style of the navbar links, without changing the theme.

**Comment by DuckyDou** [comment]
Azuriom dont use FA

**Comment by MrMicky-FR** [comment]
Hi, it’s already supported by using an icon tag in the name, like `<i class="bi bi-house"></i>  Home` :)
