### ISSUE TITLE
Small change for themes config

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/Azuriom#209]
### Description of your suggestion

🇫🇷 Salut !
Lorsqu'on est en train de modifier les configurations de son thème, il serait plus pratique que lorsqu'on sauvegarde les changements apportés on reste sur la page de configuration du thème et non retourner au menu principal des thèmes.

---------------
🇬🇧 Helloww !
When you are editing your theme configurations, it would be more convenient that when you save the changes you stay on the theme configuration page and not go back to the main theme menu.

### Advantages

🇫🇷 Pourquoi ?
Pour ceux qui ont des thèmes assez flexibles avec beaucoup de configurations (_Comme le Rainbow par exemple_), c'est assez embêtant que ça rammène à chaque fois à la page prinicpal des thèmes, c'est une petite perte de temps de la configuration car il faut le temps que la page recharge, retourner là où était dans la configuration, ce serait mieux je pense :)

-------------
🇬🇧 Why ?
For those who have flexible themes with many configurations (_like the Rainbow themes for example_), it's quite annoying that it brings back each time to the main page of the themes, it's a little waste of time of the configuration because it takes time for the page to reload, go back to where it was in the configuration, it would be better I think :)

**Comment by DuckyDou** [comment]
La suggestion du siècle!

**Comment by MrMicky-FR** [comment]
Added with https://github.com/Azuriom/Azuriom/commit/4fc6c37afa86055983bf18b82d0ba79c9de26739
