### ISSUE TITLE
Change api for mc head

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/Azuriom#210]
### Description of your suggestion

🇫🇷 Saluut !
Depuis quelques temps maintenant, plusieurs utilisateurs d'Azuriom subissent des problèmes avec les têtes qui ne s'affichent pas correctement, je viens donc apporter à ça les changements qui pourraient être effectués.

Après plusieurs recherches et tests, je suis tombé sur une API qui m'est convaincante qui est [Minotar](https://minotar.net/).
Celui-ci supporte à la fois les comptes officiels et les comptes non officiels, ce qui permettrait de ne pas utiliser deux API différentes pour les sites online/offline (_comme c'est le cas actuellement_).

- Comme je peux donner un exemple, cette API est utilisé dans le thème Rainbow pour afficher différents éléments telles que les Skins pour les podiums de votes, les meilleurs voteurs...
-----------------
🇬🇧 Hellow !
For some time now, several Azuriom users have been experiencing problems with heads not displaying correctly, so I'm here to bring to this the changes that could be made.

After several researches and tests, I came across an API that is convincing to me which is [Minotar](https://minotar.net/).
This one supports both official and unofficial accounts, which would make it possible not to use two different APIs for online/offline sites (_as it is currently the case_).

- As I can give an example, this API is used in the Rainbow theme to display different elements such as the Skins for the voting podiums, the best voters...

### Advantages

🇫🇷 Permettre de ne plus avoir le problème des têtes de Steve/Alex.

🇬🇧 Allow to fix the problem of Steve/Alex's heads.

**Comment by MrMicky-FR** [comment]
We already used Minotar before but we switched to CraftHead because there was too much issues with Minoar (see https://github.com/Azuriom/Azuriom/commit/19d1029ff607b3ec98e21c7f4f0c96d2156e234e)

However feel free to replace in your application if you want by changing the following line:
https://github.com/Azuriom/Azuriom/blob/bf6371f294ecd67c81364846c948dea581465fc0/app/Games/Minecraft/MinecraftOfflineGame.php#L27

**Comment by MrMicky-FR** [comment]
About Crafatar, we use it because it looks to the most reliable API, but it only supports UUID-based lookups. But CraftHead can also be used with UUID-based lookup.
