### ISSUE TITLE
Add an icon field for the navigation part

### ISSUE THREAD

**Issue by Sloyni** [Azuriom/Azuriom#217]
### Description of your suggestion

Add an icon field for the navigation part.

### Advantages

The possibility of adding an icon before each menu item will be very useful for the user to navigate.

**Comment by Javdu10** [comment]
You can already insert raw HTML in the navigation name

**Comment by Sloyni** [comment]
Yes but it is not visible to users, they can't know

**Comment by Sloyni** [comment]
> You can already insert raw HTML in the navigation name, see #199

Yes but it is not visible to users, they can't know
