### ISSUE TITLE
[Suggestion] Multi Game support

### ISSUE THREAD

**Issue by Mryococo91** [Azuriom/Azuriom#222]
### Description of your suggestion

it would be cool to have the possibility to have more game choices instead of only 1.

### Advantages

 I am founder of several servers on different games (Ark, Atlas, FiveM, Minecraft and Rust). Unfortunately it is impossible to display more than one different game (and also the total number on all servers)

**Comment by MrMicky-FR** [comment]
Hi, thanks for your suggestion, however this wouldn’t be possible without a major rewrite of Azuriom because of the different authentification systems used by these game: to get the UUID/XUID on Minecraft, the Microsoft login is used, but to get the SteamID on Steam games it’s a Steam login
