### ISSUE TITLE
Mojang API endpoint removed

### ISSUE THREAD

**Issue by 4winyt** [Azuriom/Azuriom#223]
### Bug description

The https://api.mojang.com/user/profiles/{uuid}/names endpoint has been removed by Mojang for ["safety reasons"](https://help.minecraft.net/hc/en-us/articles/8969841895693-Username-History-API-Removal-FAQ-) today, so everything using that API, including Azuriom, is broken. I'm not sure how much of that API Azuriom uses so another endpoint may or may not be a drop-in replacement.

### Step to reproduce

I'm not able to install Azuriom because of this but it would happen wherever else that endpoint is used.

1. Start installing Azuriom and set up the database
2. Choose Minecraft as the game type
3. Select "Yes" to "Login with Microsoft account"
4. Try to enter a valid UUID

### Web server

Apache

### Database type

MySQL

### PHP version

8.1

### Additional context

The web server, database type, and PHP version aren't very relevant but I included them anyway.

**Comment by MrMicky-FR** [comment]
Hi, thanks for this information, we will remove this soon.

Just for reference, this code is currently not used in Azuriom (but could be by plugins) since the Microsoft login addition.

**Comment by 4winyt** [comment]
> Just for reference, this code is currently not used in Azuriom (but could be by plugins) since the Microsoft login addition.

It seems to be used here in line 298 of the install script, which is why I was getting an error: https://github.com/Azuriom/Azuriom/blob/master/app/Http/Controllers/InstallController.php

**Comment by MrMicky-FR** [comment]
Thanks, forgot about this one, fixed with #225
