### ISSUE TITLE
Decimals not supported with PostgreSQL for ram column in server_stats table 

### ISSUE THREAD

**Issue by Spider-03** [Azuriom/Azuriom#224]
### Bug description

English Version Below (with google Translate)

Bonjour,

J'ai récemment mis à jour Azuriom en v 1.0.8 
Je me sert de AZlink pour un serveur Minecraft (Paper 1.19.2).

Dans ma console minecraft j'ai toutes les 15 minutes

![image](https://user-images.githubusercontent.com/113440075/190450506-341a683e-31c3-45ec-8099-17ad4d9a5165.png)

Côté logs laravel j'ai ceci : 

https://paste.gg/p/anonymous/7d7f73bab54d43fc8771e305b29db521

En espérant que vous puissiez corriger cela rapidement.
Joignable sur Discord Spider#2958

Cordialement,

-------------

Hello,

I recently updated Azuriom to v 1.0.8
I use AZlink for a Minecraft server (Paper 1.19.2).

In my minecraft console I have every 15 minutes

![image](https://user-images.githubusercontent.com/113440075/190450506-341a683e-31c3-45ec-8099-17ad4d9a5165.png)

Side laravel logs I have this:

https://paste.gg/p/anonymous/7d7f73bab54d43fc8771e305b29db521

Hope you can fix this soon.
Joinable on Discord Spider#2958

Regards,

### Step to reproduce

English Version Below (with google Translate)

Je ne sais pas si en réinstallant de 0 l'erreur réapparaitrait ou pas.

-------------
I don't know if by reinstalling from scratch the error would reappear or not.

### Errors / Logs

https://paste.gg/p/anonymous/7d7f73bab54d43fc8771e305b29db521

### Web server

Nginx

### Database type

PostgreSQL

### PHP version

8.1

**Comment by MrMicky-FR** [comment]
Hi, can you tell me if using replacing the content of the file `app/Models/ServerStat.php` with this ones fixes this error ? https://gist.github.com/MrMicky-FR/c942477ff95baea62cef490be8a950ba
