### ISSUE TITLE
[Forum] Add a Webhook Discord

### ISSUE THREAD

**Issue by Shykuzo** [Azuriom/Azuriom#226]
### Description of your suggestion

When you create a Forum / Sub-Forum / ..., you have a box where you can indicate the link of a Webhook Discord.

When a message is posted in this Forum / Sub-Forum / ..., an Embed Discord (Customizable, if possible) is sent to the Webhook channel indicated in the configuration.

Useful to know when there are new applications, new bugs reported, ...

### Advantages

- Allows you to know when a message is posted.
- Prevents not seeing a message.
- Allows to make logs.

**Comment by MrMicky-FR** [comment]
Added in v1.0.7 of the forum
