### ISSUE TITLE
Translate markdown editor texts

### ISSUE THREAD

**Issue by LucasB25** [Azuriom/Azuriom#228]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/50886682/192650616-7419be7a-c34a-4924-86b9-0799221bb93c.png">
Quand on clique sur ce bouton impossible de faire retour en arrière.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/50886682/192650701-248a447f-80d3-4748-bc2b-575f33a48f1e.png">
Quand on clique sur ce bouton impossible de faire retour en arrière.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/50886682/192650756-5789a64f-5df2-4fd0-8372-4d27a477094e.png">
Ce qui est en jaune n'a pas été traduit en français alors, moi je l'ai traduit donc il est donc en français mais normalement ce n'est pas le cas.

**Comment by MrMicky-FR** [comment]
Concernant le problème du plein-écran, cela semble venir du thème, il faudrait le signaler au développeur du thème utilisé.

**Comment by LucasB25** [comment]
> Concernant le problème du plein-écran, cela semble venir du thème, il faudrait le signaler au développeur du thème utilisé.

Ok je signale ça
