### ISSUE TITLE
Add support for MCBE servers

### ISSUE THREAD

**Issue by Alemiz112** [Azuriom/Azuriom#23]
Hello, would you be able to add support for Minecraft: Bedrock servers?

**Comment by Nu4h-dev** [comment]
good idea

**Comment by towuk118** [comment]
GEYSER USE BRO!) Geysermc

**Comment by towuk118** [comment]
create java server and add plugin geyser-spigot :)

**Comment by Alemiz112** [comment]
Using geyser is not option to support MCBE query. Geyser is protocol translator application to allow players join MC Java servers. If your network is MCBE related why would you use it?

**Comment by towuk118** [comment]
> Using geyser is not option to support MCBE query. Geyser is protocol translator application to allow players join MC Java servers. If your network is MCBE related why would you use it?

You will planed add support mcbe servers? Like a BedrockDedicatedServer, PocketMine(altay), nukkitX?

**Comment by MrMicky-FR** [comment]
Added in 6a452a414b4091c59a40a6d92dce8f50174a60c6 🎉 Will be available in the next release

**Comment by Alemiz112** [comment]
Awesome!
