### ISSUE TITLE
responsive phone logs

### ISSUE THREAD

**Issue by LucasB25** [Azuriom/Azuriom#230]
### Bug description

![image](https://user-images.githubusercontent.com/50886682/192986451-142e6e8e-c3ed-4dd3-929f-fb6358671bcd.png)
soucis de centrage avec le background
afficher un nom limite pas afficher la totalité de la suite

![image](https://user-images.githubusercontent.com/50886682/192987190-4d7f7c44-6ad9-469d-8434-98c3258f5a5b.png)
![image](https://user-images.githubusercontent.com/50886682/192988952-602960c8-a167-4e62-a567-a00a39ddc217.png)
![image](https://user-images.githubusercontent.com/50886682/192989044-7299d496-f06a-450d-b998-10970bc66ad1.png)

Sois retiré la date et l'heures sois réduire avec seulement la date JJ/MM

![image](https://user-images.githubusercontent.com/50886682/192987651-8553addd-8d40-4137-8365-455cabad7a10.png)
boutons coller 

![image](https://user-images.githubusercontent.com/50886682/192987786-5b8ab758-006c-414a-9e64-66b24c49cbfb.png)
![image](https://user-images.githubusercontent.com/50886682/192987990-5019c3cf-c15c-42c2-b85e-5cd4ff2f8aee.png)
on vois asbolument pas le boutons de téléchargement

![image](https://user-images.githubusercontent.com/50886682/192988133-b75bff1f-dbf5-453c-bddc-81ae4e40597c.png)
![image](https://user-images.githubusercontent.com/50886682/192988416-00ff7d27-1ecc-4973-b131-01cf3973df94.png)
![image](https://user-images.githubusercontent.com/50886682/192988528-70fb4fe4-5499-43ed-a992-cc58e624ba6b.png)
![image](https://user-images.githubusercontent.com/50886682/192989195-bb4c8db0-3378-4251-abfd-14ec1f2d0111.png)

aucun visibilité sur le dernier mots

![image](https://user-images.githubusercontent.com/50886682/192988665-44269e32-8e7e-4934-9fa2-53900074188f.png)
aucun visibilité sur les derniers mots + boutons coller

**Comment by MrMicky-FR** [comment]
For tables, just use horizontal scrolling:

https://user-images.githubusercontent.com/30863452/192989179-e108c78e-4b5c-4561-8830-9d87b50380d9.MOV

Merging remaining issues in #229

**Comment by LucasB25** [comment]
I import the worries in the other .

**Comment by MrMicky-FR** [comment]
I’ve updated the comment, shoud be good 👍

**Comment by LucasB25** [comment]
But I can’t make a pull requests
