### ISSUE TITLE
Lien cliquable visible sans passer ça sourit dessus

### ISSUE THREAD

**Issue by LucasB25** [Azuriom/Azuriom#232]
### Description of your suggestion

Alors j'ai un doute si c'est propre au thème ou au cms alors je suggest quand même ici

Quand tu passes ta sourit un lien clicable changer de couleur mais ce serait sympa qu'il soit de la couleur de manière permanente

exemple: 
<img width="116" alt="image" src="https://user-images.githubusercontent.com/50886682/193360843-8c27b820-8586-47be-904b-d633d37247b0.png">
qu'il soit de manière permanente comme ça pour pouvoir des différencier des textes classiques

**Comment by MrMicky-FR** [comment]
C’est lié au thème, dans le doute il suffit de désactiver le thème et de tester
