### ISSUE TITLE
Option for users to downloads their user data 

### ISSUE THREAD

**Issue by thefourcraft** [Azuriom/Azuriom#233]
### Description of your suggestion

In the modern world, privacy is paramount, and adding the option for users to request and download their data is crucial.

# A New User Porfile Feture
In the user management tab (where the users can change their settings on the website) add an option to download all their account data from the SQL database.
This is a started thing on a lot of websites and would be a very nice feature to have in [Azuriom](https://github.com/Azuriom/Azuriom). 
This will automatically make every single azuriom website compliant with the GDPR and the CPPA (assuming they have a privacy policy and TOS). 
This Small change will help to increase the user trust across all the websites that are powered by Azuriom CMS.
Because today privacy is essential in every organization.

# What Is GDPR?
The General Data Protection Regulation (EU) (GDPR) is a [regulation](https://en.wikipedia.org/wiki/Regulation_(European_Union)) in [EU law](https://en.wikipedia.org/wiki/EU_law) on [data protection](https://en.wikipedia.org/wiki/Data_protection) and privacy in the [European Union](https://en.wikipedia.org/wiki/European_Union) (EU) and the [European Economic Area](https://en.wikipedia.org/wiki/European_Economic_Area) (EEA). The GDPR is an important component of EU [privacy law](https://en.wikipedia.org/wiki/Privacy_law) and of [human rights law](https://en.wikipedia.org/wiki/Human_rights_law), in particular Article 8(1) of the [Charter of Fundamental Rights of the European Union](https://en.wikipedia.org/wiki/Charter_of_Fundamental_Rights_of_the_European_Union). - Wikipedia
# What Is CPPA?
This: https://cppa.ca.gov/ it's the same as the GDPR but for Californian residents.

### Advantages

Adding this small change will make ensure Azuriom's relevancy in the modern fast-changing world.
Not only that, but this will make Azuriom compliant with all the other privacy [initiatives by different countries around the world](https://unctad.org/page/data-protection-and-privacy-legislation-worldwide)
it's the right step forward for every organization!
## [#PrivacyMetters ](https://privacyinternational.org/learning-resources/privacy-matters)

**Comment by ArnaudLier** [comment]
This package could be used to do the heavy lifting: https://github.com/spatie/laravel-personal-data-export

**Comment by MrMicky-FR** [comment]
Hi, just changed the title to prevent confusions: Azuriom is already GPDR compliant and this **isn’t required** to comply with RGPD, as long as you send the data on manual user request.

But I also think it could be a nice feature :)

**Comment by MrMicky-FR** [comment]
After some reflections, this would be more suitable as a plugin to simplify handling data exporting from other plugins (to prevent circular dependencies)

**Comment by thefourcraft** [comment]
# Amzing ❤
