### ISSUE TITLE
Payer pour retirer les footers d'Azuriom

### ISSUE THREAD

**Issue by Margouta** [Azuriom/Azuriom#235]
### Description of your suggestion

Comme chez d'autre CMS (CMW) [https://craftmywebsite.fr/](https://craftmywebsite.fr/), on peut payer 10€ pour retirer les Crédits. [https://craftmywebsite.fr/acheter/licence/](https://craftmywebsite.fr/acheter/licence/) !
Merci =)

**Comment by MrMicky-FR** [comment]
Duplicate of #149

**Comment by MrMicky-FR** [comment]
Pour donner plus de détails : le code d’Azuriom est proposé sous la licence GPL v3 qui demande de garder le copyright et s’applique à tout le monde. Proposer une solution payante qui violerait notre propre licence serait extrêmement contre-productif et assez hypocrite selon moi.
