### ISSUE TITLE
Language Switcher

### ISSUE THREAD

**Issue by n0tMarvin** [Azuriom/Azuriom#242]
### Description of your suggestion

Im suggesting a Language Switcher on the Homepage itself.
So the User / Player can use his prefered language.

Admins could configurate the phrases etc

### Advantages

Makes much sense for multilangual Communitys

**Comment by MrMicky-FR** [comment]
This would be a great feature, but unfortunately this would be too complicated to implement in a proper way: all the built-in messages of Azuriom and it's plugins can be translated (and are also translated in many languages), but all the website's content (settings, pages, posts, navbar, roles, shop items, wiki pages, FAQ questions, etc, etc) couldn't be translated in multiples different languages without massive changes.

Because of this, the result of adding a language switcher would be half-translated website which wouldn't make much sense.

**Comment by thefourcraft** [comment]
[Azuriom](https://github.com/Azuriom/Azuriom) is open source if you want to add it, just code that in if you want to 
My Dev did some testing with multi langs and RTL support with larval
And we are still working on that... as @MrMicky-FR said it's complicated but not impossible 
we will test it and I push it to [Azuriom](https://github.com/Azuriom/Azuriom)
but we have quite a long prosses

- [ ] Intgration with the admin meue (eg: for limiting langs)
- [ ] Integration with different plugins and themes (they all have to work with the new changes)
- [ ] General performance (if some user spams it)
- [ ] also support for RTL - the website contact has to switch sides... and it has to work with all the above

@n0tMarvin this is why its kinda complicated 😅 despite we will get there 😉 (I hope)

https://user-images.githubusercontent.com/90725541/197590556-9d1c1284-1338-4fc9-8ed9-55d72e33bf8f.mp4

Also white 👁

**Comment by n0tMarvin** [comment]
Well im not a Dev, thats why i suggested it. But glad someone looks to it! Nice keep it up!

**Comment by n0tMarvin** [comment]
@MrMicky-FR 

I saw that Jav has an open Pull Request with exactly that feature. So i guess it just needs some re-check?

**Comment by MrMicky-FR** [comment]
> @MrMicky-FR
> 
> I saw that Jav has an open Pull Request with exactly that feature. So i guess it just needs some re-check?

The PR is out-of-date, I've closed it with more explanations

**Comment by thefourcraft** [comment]
I also have done some progress, but it's not stable at all
I wanted to take a simpler approach to this issue
by changing the language based on existing language translation for Azuriom

I have talked with @Sloyni about this

> me and my laravel dev, the whole point of the new lang dropdown is just to change the website for RTL and LTR
I think it will be possible if Azuriom had a global lang indicator 
we already have the translation selection system

## What Dose it means?
Basically change the display language for the user, using the existing translations for Azuriom.
the one in `/language` folder

**Comment by Javdu10** [comment]
The code you are looking for is here: https://github.com/Azuriom/Azuriom/pull/73/files

It's a simple language switcher per user

**Comment by thefourcraft** [comment]
@Javdu10 but @MrMicky-FR said that
> The PR is out-of-date, I've closed it with more explanations

So it needs to be updated in order to work? or its working and @MrMicky-FR didn't merge it because of conflicts?

**Comment by MrMicky-FR** [comment]
> @Javdu10 but @MrMicky-FR said that
> 
> > The PR is out-of-date, I've closed it with more explanations
> 
> So it needs to be updated in order to work? or its working and @MrMicky-FR didn't merge it because of conflicts?

As I said, full explanations are available in the PR last-comment

**Comment by n0tMarvin** [comment]
But why closing it? Why not just making it work then? Its an awesome feature

**Comment by thefourcraft** [comment]
why are we taking such a complicated approach to localization, @Javdu10 your pull is good but it's too compacted and will change a lot of things
## Here are some ideas 💡
### Categories 📃
we can solve the problem by making categories for FAQ & Posts
and they can be used for multiple things but people can also create categories for languages
__example:__
```
.
├── FAQ English       # For All English FAQs
└── FAQ Greman      # For All Greman FAQs
```
Also, we can take this a step further and make subcategories then people will be able to sort out by language and topics
__example:__
```
.
├──English   # For all English Posts 
│   ├── Updates  #subcategorie 
│   ├── Commands  #subcategorie
│   └── Servers  #subcategorie
├── German                    # For all German Posts
│   ├── Aktualisierung          #subcategorie
│   ├── Befehle        #subcategorie
│   └── Server                #subcategorie
└── French
```
#### Plugins
The wiki plugin already has categories and we can create master categories that
The shop & Forum plugins are the same principles 

#### Pros & Cons
##### Pros
- Simple integration
- No need to update a lot of code and break compatibility
- Can be done individually for each plugin
- Using existing functions 
##### Cons
- A lot of files (if you have a big wiki or a big FAQ list)

### Simpler Localization🤏
we already have translations for Azuriom, the files are in place.
why not make a simple lang switch that will change the lang based on those files?
(that's what I am trying to do)
Here is an example with an @Sloyni Modified them for RTL support (While the future doesn't acutely switch languages you can get a general idea)
https://user-images.githubusercontent.com/90725541/200286598-bda7dc0d-0086-446e-99d0-206a052932a7.mp4
we can save this to a cookie or to the database (not recommended)
***
I don't think that making a localization system is impossible, we just need to think outside the box 😉

**Comment by thefourcraft** [comment]
> But why close it? Why not just make it work then? It's an awesome feature @n0tMarvin 

Here Is Why:

> > Closing this for now, as this PR is out-of-sync and not compatible with Azuriom v1.0.
Also, this feature would be great., but unfortunately it would be too complicated to implement in a proper way: all the built-in messages of Azuriom and its plugins can be translated (and are also translated in many languages), but all the website's content (settings, pages, posts, navbar, roles, shop items, wiki pages, FAQ questions, etc, etc) couldn't be translated in multiples different languages without massive changes (see https://github.com/Azuriom/Azuriom/pull/46) - @MrMicky-FR

**Comment by n0tMarvin** [comment]
@MrMicky-FR is that not reason enough to implent it already?

**Comment by MrMicky-FR** [comment]
The reason of half translated content is still valid, and a plugin could implement this if it’s limited to a language switcher

**Comment by Javdu10** [comment]
> The reason of half translated content is still valid, and a plugin could implement this if it’s limited to a language switcher

It was not half translated, specially with https://github.com/Azuriom/Plugin-Shop/pull/15, https://github.com/Azuriom/Plugin-Wiki/pull/4 and https://github.com/Azuriom/Plugin-FAQ/pull/3 some other could be done but i didnt waste more time since it was not seriously considered.

The plan was to have it deep into the CMS to be multi lingual for v1, not "just" a language switcher

**Comment by thefourcraft** [comment]
> To be honest I got tired of this because I've put hours in this, did the work and the only feedback I got was "it's complicated it will change many components" as you could see the components were changed and it was supposed to be in v1, never got serious consideration apart from "we will see later" the functionality is in production on two websites: 
https://universe.flyff.com and https://moonflyff.fr

wow, so it does work! I can just update it to the latest Azuriom version myself and deploy it... ?

@Javdu10 just saying the website looks amazing, I didn't believe that it's powered by Azuriom 😲
I am impressed, the websites look fantastic 🤯

> The original plan was to have it deep into the CMS to be multi-lingual for v1, not "just" a language switcher
It's never to late @MrMicky-FR

**Comment by n0tMarvin** [comment]
I told you lmfao.
And this should just be implemented for everyone. It exists already....

**Comment by KvasirQc** [comment]
Hi do you have any update regarding this. 

Azuriom main website supports multiple languages, but my delexe theme is not working. I contact the theme creator and he asked me to contact azurium and to tell you this:

"Demande leurs d'ajouter une route qui permet de changer de langue"
"Ask them to add a route that give us the ability to switch languages"

I really appreciate the theme that I working with at the moment, but I wanna create a tri-lingual website. Please help us with that issue!

I'm french, if you need help translating some texts, I could help for sure!

have a nice day!
