### ISSUE TITLE
Force Password Reset

### ISSUE THREAD

**Issue by n0tMarvin** [Azuriom/Azuriom#244]
### Description of your suggestion

Add an Function that forces every user to change its Password (incase of a DB Leak or compareable)

**Comment by MrDoudou** [comment]
MR: https://github.com/Azuriom/Azuriom/pull/339

**Comment by MrMicky-FR** [comment]
Hi @n0tMarvin, it could be a nice feature but I’m not sure to see how it would be useful : all passwords are hashed in database, so even in the case of a DB leak, it’s impossible for the attackers to retrieve the password so they won’t be able to login even with the hashed password

**Comment by MrDoudou** [comment]
It is possible for a user to give it in raw form in a public channel.
