### ISSUE TITLE
Show staff on site

### ISSUE THREAD

**Issue by Snordin** [Azuriom/Azuriom#248]
### Description of your suggestion

With the staff plugin its really easy to add some random staff to the site.
In my eyes i think its better to code this feature inside the cms. and make it works with the users/roles from azuriom.
Like when u give a user a role. this role is visible as group on the website as moderator(group)
Same for admins and other custom roles u can create. 
Also possible if when u click on a staff member u go to his profile see some information about the user.
Registration date, last seeen, rank, birthday, bio.

### Advantages

Getting the staff plugin a major change.

**Comment by MrMicky-FR** [comment]
This would be a great addition to the existing staff plugin, you should open an issue on the Staff plugin GitHub repo: https://github.com/Linedev-Azuriom/Plugin_Staff
