### ISSUE TITLE
Be able as player to change our name

### ISSUE THREAD

**Issue by Soifox** [Azuriom/Azuriom#250]
### Description of your suggestion

Being able as player (or admin by forcing it) to change our name on the forum / website and that the name keep itself.

### Advantages

Really usefull for rôleplay server (Gmod)

**Comment by vassilidev** [comment]
I will do it today, how can it be ?

All users can ?

A toggle option from admin ?

**Comment by MrMicky-FR** [comment]
Yes, a field in the profil, with an option in the admin panel, limited to games without OAuth login seems to good to me

**Comment by MrMicky-FR** [comment]
Same field would be good :)

**Comment by vassilidev** [comment]
And what about the UUID generated ? Keep it the same ?
