### ISSUE TITLE
Shop Timings

### ISSUE THREAD

**Issue by OfficialAudite** [Azuriom/Azuriom#252]
### Description of your suggestion

Add so the packages can give role for a period of time.
If I have a package that is VIP I would love to have it timed so it disappear later on from that user.

### Advantages

Easy to manage VIP or other timed packages.

**Comment by MrMicky-FR** [comment]
This can already be done by the permission system on the game server with temporary permissions

Closing this as it’s a duplicate of Azuriom/Plugin-Shop#31
