### ISSUE TITLE
Sync Discord role

### ISSUE THREAD

**Issue by LucasB25** [Azuriom/Azuriom#254]
Ajouté des réduction selon un rôle Discord; exemple pour le rôle de boost discord. Pendant le temps où la personne possède ce rôle il reçoit une réduction tout le long de sont boost. ça permettrait d'éviter de regarder à chaque fois si la personne a ce rôle et de lui donner la réduction à la main.

Et aussi d'ajouter la possibilité de donner un rôle selon le grade que la personne à acheter ou du moins open l'api le permettant.
Soit crée un module npm pour link directement entre le site et le bot discord, soit open source l'api.

**Comment by Jotiprime** [comment]
Yes, please, implement the function that users can link their discord account and thus they are automatically given the role.

**Comment by crashzk** [comment]
It would be interesting to allow connecting the discord server to Azuriom, so we can even execute commands in discord, assign roles in discord when the player buys a product in the shop, etc.

**Comment by raykai** [comment]
> It would be interesting to allow connecting the discord server to Azuriom, so we can even execute commands in discord, assign roles in discord when the player buys a product in the shop, etc.

I would love to have this option too.

**Comment by MrMicky-FR** [comment]
Discord roles synchronization is now available in private-beta for [GitHub sponsors](https://github.com/sponsors/Azuriom) 🎉 It will be added in Azuriom v1.1.0 (no ETA for now)
![discord-bridge](https://user-images.githubusercontent.com/30863452/219967685-8947e561-3e23-4976-b9b4-4d11d0e5546d.gif)

**Comment by crashzk** [comment]
@MrMicky-FR apenas um feedback, acho que seria interessante também mostrar o **Discord ID** do usuário no perfil, como tem para SteamID.

![image](https://user-images.githubusercontent.com/32937653/220933694-4a804e54-8edc-48b5-9026-2efb762bcded.png)

![image](https://user-images.githubusercontent.com/32937653/220933737-089215d5-bc78-4868-93b7-627105578f4b.png)

**Comment by MaximusMcfly** [comment]
When will this be available, id love to add a sync between my discord and my website

**Comment by MrMicky-FR** [comment]
> When will this be available, id love to add a sync between my discord and my website

@MaximusMcfly This is already available for GitHub sponsors, and for the general availability the answer is in my previous comment :

> Discord roles synchronization is now available in private-beta for [GitHub sponsors](https://github.com/sponsors/Azuriom) 🎉 It will be added in Azuriom v1.1.0 (**no ETA for now**)
