### ISSUE TITLE
Plesk

### ISSUE THREAD

**Issue by Jpofin** [Azuriom/Azuriom#26]
Does this work in plesk?

Installing seems to work, however the page looks like that now:
![image](https://user-images.githubusercontent.com/35976294/88690078-91d14080-d0fb-11ea-9724-74835d2c568b.png)

**Comment by MrMicky-FR** [comment]
Yes it can work with Plesk, this issue can be caused by a permission problem or URL rewrite problem, if you need help you can join our [Discord server](https://azuriom.com/discord) for easier support

**Comment by FisaGamer** [comment]
Good evening,

Yes it does very much work with plesk as I use it daily.
@Jpofin
