### ISSUE TITLE
User money transfer on Steam

### ISSUE THREAD

**Issue by MaXx-62** [Azuriom/Azuriom#265]
### Bug description

Money transfer not working on rust panel
(I use the Rainbow theme)

[Screen 1](https://prnt.sc/AwWPaCwK4Mm3)
[Screen 2 ](https://prnt.sc/3YAg_oCsNHul)

### Step to reproduce

To reproduce it you install the rust panel, then you look at the profile the small money transfer panel does not appear because it is deactivated by default, then you will activate it, you return to the profile and the transfer panel money is still not there!

(I use the Rainbow theme)

### Web server

Nginx

### Database type

MySQL

**Comment by MrMicky-FR** [comment]
Hi, can you test without the theme to see if the issue is solved? And id it’s the case the issue should be reported to the theme developer

**Comment by Max62800** [comment]
> 

Yes not work too with no theme

[Image 1](https://prnt.sc/ke_m1eT6oTfp)

**Comment by MrMicky-FR** [comment]
Whoops, wrong issue number in the commit
