### ISSUE TITLE
Adding a Donation page

### ISSUE THREAD

**Issue by ItJustFox** [Azuriom/Azuriom#266]
### Description of your suggestion

Adding a plugin or directly inside the Azuriom an donation page has we cant make them directly with the plugin of Shop

### Advantages

Would be more better than making like "donation of 5$" ect ect in shop plugin, and could allow to make top donator ect like in plugin of vote

**Comment by lapetitehanae** [comment]
Hello, i can do it for you.
Send me a message: hanae#2022

**Comment by MrMicky-FR** [comment]
Hi, thanks for your suggestion but unfortunately we are not keeping suggestions for entirely new plugins as we prefer focus on adding the suggestions for existing plugins (and there are quite a few!)
