### ISSUE TITLE
Microsoft login doesn't work any ideas?

### ISSUE THREAD

**Issue by Dotta4You** [Azuriom/Azuriom#269]
### Bug description

Here 
https://clipchamp.com/watch/zIs05a9wtuh
See 

### Step to reproduce

Microsoft login lol

### Errors / Logs

Only that

[laravel-2022-12-05.log](https://github.com/Azuriom/Azuriom/files/10188178/laravel-2022-12-05.log)

### Web server

Apache

### Database type

MariaDB

### PHP version

8.1

### Additional context

Users can't login or Register. 
The user is not created at all

**Comment by thefourcraft** [comment]
I also had issues integrating it, when I do the prosses again I will try to answer this

**Comment by MrMicky-FR** [comment]
Seems like the link isn't working anymore
