### ISSUE TITLE
Displays the same Articel and It's Buggy 

### ISSUE THREAD

**Issue by Dotta4You** [Azuriom/Azuriom#270]
### Bug description

In the posts, if you only posted the 1st post, the same post will be displayed again in the post. It also says "theme::theme.news.last-news".

### Step to reproduce

Goto Posts and see 

### Errors / Logs

No errors

### Web server

Apache

### Database type

MariaDB

### PHP version

8.1

### Additional context

See

![HCdwuea](https://user-images.githubusercontent.com/81478049/206788674-f16bbcb6-ec43-45fb-909e-19fce415688c.png)

**Comment by MrMicky-FR** [comment]
Please see with the theme developer as we can’t do anything about this issue if it’s related to the theme
