### ISSUE TITLE
  Add message that if the microsoft account don't have Minecraft the account could not be created

### ISSUE THREAD

**Issue by Dotta4You** [Azuriom/Azuriom#271]
### Description of your suggestion

Add message when signing up with Microsoft account if it doesn't have an MC...

**Comment by MrMicky-FR** [comment]
Hi, it should already be the case. If you have an internal error, make sure to provide the logs, otherwise if you just don't have any message after a login attempt, make sure to try without any theme enabled. Feel free to comment in this issue so it can be reopened if needed :)
