### ISSUE TITLE
Handle Xbox response code to improve UX

### ISSUE THREAD

**Issue by magrigry** [Azuriom/Azuriom#275]
### Description of your suggestion

Sometimes the Xbox oAuth2 flow may return an error code, e.g. `Invalid Xbox response: 2148916238`

This error code leads to an HTTP 500 error, which is bad for UX.

[Here](https://learn.microsoft.com/en-us/answers/questions/583869/what-kind-of-xerr-is-displayed-during-xsts-authent-1.html) is a list of error codes and their meaning (maybe not exhaustive) 

> 1) [2148916233](https://learn.microsoft.com/en-us/answers/questions/583869/what-kind-of-xerr-is-displayed-during-xsts-authent-1.html) - Microsoft account does not have an Xbox account.
> 2) [2148916235](https://learn.microsoft.com/en-us/answers/questions/583869/what-kind-of-xerr-is-displayed-during-xsts-authent-1.html) - Accounts from countries where XBox Live is not available or banned.
> 3) [2148916236](https://learn.microsoft.com/en-us/answers/questions/583869/what-kind-of-xerr-is-displayed-during-xsts-authent-1.html) - You must complete adult verification on the XBox homepage. (South Korea)
> 4) [2148916237](https://learn.microsoft.com/en-us/answers/questions/583869/what-kind-of-xerr-is-displayed-during-xsts-authent-1.html) - Age verification must be completed on the XBox homepage. (South Korea)
> 5) [2148916238](https://learn.microsoft.com/en-us/answers/questions/583869/what-kind-of-xerr-is-displayed-during-xsts-authent-1.html) - The account is under the age of 18, an adult must add the account to the family

Azuriom could handle those error code and display a proper message to the end user 

### Advantages
* Improve UX 
* Avoid people asking for help in game server’s support channel or Azuriom support channel

**Comment by MrMicky-FR** [comment]
Added in https://github.com/Azuriom/Azuriom/commit/126e89e6dcac0cdff3f3d35467efa3fa35b52163 👍
