### ISSUE TITLE
Minecraft avatar refress

### ISSUE THREAD

**Issue by aws0jam** [Azuriom/Azuriom#276]
### Bug description

If I install the skinapi plugin (minecraft) and upload the skin, the profile avatar is not updated because the browser is cash image

### Step to reproduce

I upload the skin, the image does not update even if I close the browser. But if I delete the cash, then it's fine. With this I was able to make it not save the image. ?x=<?php echo time(); ?> after avatar image

### Web server

Apache

### Database type

MySQL

**Comment by MrMicky-FR** [comment]
Please open an issue in the related plugin

**Comment by aws0jam** [comment]
I don't think there is a problem with the plugin, because if I manually update the avatar it works. But ok, I'm writing for the plugin.
