### ISSUE TITLE
Prevent modifications of users with higher role

### ISSUE THREAD

**Issue by xApafaas** [Azuriom/Azuriom#277]
### Description of your suggestion

Bonjour, bonsoir

Ma suggestion:
Empêcher de pouvoir modifier les utilisateurs ayant un rang supérieur (compatible avec la fonctionnalité dans Panel Admin > Grades [Placement des rangs])

### Advantages

Ajouter une sécurité au Panel ainsi qu'au projet utilisant ce CMS

**Comment by MrMicky-FR** [comment]
Cette fonctionnalité est déjà disponible dans Azuriom
