### ISSUE TITLE
[Api AzAuth] Introuvable au niveau de l'URL

### ISSUE THREAD

**Issue by WavesOfNight** [Azuriom/Azuriom#278]
### Bug description

Bonjour,

Il y a peut de temps avec un amis nous avons ouvert un site avec Azuriom, tout fonctionne parfaitement sauf l'API AzAuth, premièrement elle inaccessible au niveau de l'URL "**Erreurs 404 Page non trouvée La page que vous cherchez n'a pas pu être trouvée.** et sur mon programme l'erreurs signifie pratiquement la même choses il est dans l'incapacité de créer un tunnel pour l'api 

Cordialement 
![image (1)](https://user-images.githubusercontent.com/92826596/210233073-75389586-c06e-46b4-b389-c6dc86a7b3ee.png)
![image (2)](https://user-images.githubusercontent.com/92826596/210233111-71318f7b-52d2-4f62-ad1d-d0563f6af5f0.png)

### Step to reproduce

taper l'url du site plus le /api/auth

### Database type

MySQL

### PHP version

8.0

**Comment by WavesOfNight** [comment]
PS C'est pour relier un système launcher avec

**Comment by MrMicky-FR** [comment]
Comme indiqué dans la [documentation](https://azuriom.com/fr/docs/api-auth#utilisation-hors-java), il faut utiliser les endpoints `/api/auth/authenticate`, `/api/auth/verify` ou `/api/auth/logout`

**Comment by WavesOfNight** [comment]
J'ai déjà fait tout cela même dans mon code toujours l'erreurs 404 avec le problème persiste  
![api](https://user-images.githubusercontent.com/92826596/210237313-2dbb0a7f-0e2e-47b5-a5e8-0bc093ec2d26.png)
