### ISSUE TITLE
Not a correct translation

### ISSUE THREAD

**Issue by nsavchin** [Azuriom/Azuriom#279]
### Bug description

In the control panel, when choosing the Ukrainian language, "Англійська" (English) is written, but it should be "Українська" (Ukrainian)

![image](https://user-images.githubusercontent.com/60260972/210386204-116c22b7-217f-472d-80c4-054a3c9ccb1b.png)

### Step to reproduce

In <code>resources\lang\uk\messages.php</code>
```
return [
 'lang' => 'Українська',
];
```

### Database type

None

**Comment by MrMicky-FR** [comment]
Thanks for reporting this, I’ve fixed it on [Crowdin](https://translate.azuriom.com) and it will be available in the next Azuriom release :)
