### ISSUE TITLE
Forum Additions

### ISSUE THREAD

**Issue by OliverP98** [Azuriom/Azuriom#282]
### Description of your suggestion

With the forums it has been easy to use for our community, but we have come accross some features which could enhance our experience.

1. Increase the number of posts which are within the lastest posts section from 3 to many more or to an ammount which could be set in the setting for the forums. This could even be a new page which lists the lastest posts for which that user can see and it lists the last 15 lastest posts.

2.  A way to determine between read and unread forum topics changing back to unread when a new post within a thread is made, it would make finding new posts easier. This could be by having brighter icon for unread posts.

### Advantages

The advantages of this would be to help users engage effectively with the forums and allowing the forums to show them quickly updates, unread posts and areas they should put their focus. This would also make our users more likely to use the forums more to communicate on specific topics.

**Comment by WEEZOOKARP** [comment]
I second this

**Comment by MrMicky-FR** [comment]
1. Added in [forum update v1.0.11](https://market.azuriom.com/resources/16/updates).
2. This would be pretty database-intensive as it would require tracking all activities of all members
