### ISSUE TITLE
URL rewrite enabled

### ISSUE THREAD

**Issue by Chriskm2001** [Azuriom/Azuriom#283]
### Bug description

It say I have all requirements other than the "URL rewrite enabled"
But when I aks the web hosting i am hosting with, they say URL rewrite is enabled by default on their server, and I have tried putting the .htaccess inside the main folder I want to install it on and in the public folder it comes with

**Comment by MrMicky-FR** [comment]
Please use Discord for support as this is unlikely to be an issue with Azuriom itself as it works fine for more than a thousand websites

**Comment by Chriskm2001** [comment]
I tried on there yesterday, but have gotten no response
