### ISSUE TITLE
[Forum] using forum name instead of id as link identification

### ISSUE THREAD

**Issue by MsEDok** [Azuriom/Azuriom#285]
### Description of your suggestion

Forum title: This is a test forum
current forum `/forum/discussions/2`

new forum `/forum/discussions/this-is-a-test-forum.{random_num}`

{random_num} is for duplicate forum name

### Advantages

it more "google" friendly to search for and it user friendly to see what the link/forum is without going into it

**Comment by vassilidev** [comment]
Somthing like a slug ?

**Comment by raykai** [comment]
yes having it as a slug would be nice!

**Comment by MrMicky-FR** [comment]
Added in version 1.0.16 of the forum
