### ISSUE TITLE
User not logged in custom pages while Maintenance is enabled

### ISSUE THREAD

**Issue by Certurix** [Azuriom/Azuriom#286]
### Bug description

When you enabled your Maintenance but disabled it on every pages of your website and you configured some paths to block, the others pages who are not blocked make the current user logged in to be logged out and show the Login/Register templates inside every themes.
It seems the bug affect only custom pages.

TL;DR :
Custom pages show "Login/Register" instead of your current profile when Maintenance is enabled & blocked paths are configured.

### Step to reproduce

First, login with your admin account (and you can test it also with an user account)
Enable Maintenance, but disable for every pages
Configure some paths to block
Create a custom page and then access it (Make sure its a public page)
**You'll notice you are logged out**
If you try to login/register, you'll be redirected to the / route.

### Database type

None

### Additional context

Tested only in Beta AzuriomCloud with Steam Version. You may test a self-hosted instance with Minecraft and others Steam games to ensure the bug is not a specific case.

**Comment by MrMicky-FR** [comment]
I can't reproduce this issue, can you confirm it's also present on standalone version of Azuriom ? Also which user is logged out on the page, the admin (which can view the page) or the member (which see the maintenance page) ?

**Comment by Certurix** [comment]
Unfornately, I cannot test it on a standalone version, even in a local server. The user who is logged out are users who have access to pages while the maintenance mode is on. (So every users who have "Access to the website while maintenance" permission will have this issue).

I'll upload a video to show the bug.

**Comment by MrMicky-FR** [comment]
Also tested with a non-admin user with maintenance permission but unfortunately I can't reproduce the bug on self-hosted Azuriom
