### ISSUE TITLE
Add a sign that username must be the same than in game.

### ISSUE THREAD

**Issue by Jotiprime** [Azuriom/Azuriom#289]
### Description of your suggestion

In the registration, they should clarify that the username has to be the same as in the game (for example in non-premium minecraft) If not, when you buy something, it is given to that username. It must be specified somewhere. It would also be nice to let the username change.

### Advantages

Avoid confusion on the part of users.

**Comment by MrMicky-FR** [comment]
This is more a suggestion for the theme (or modify the theme)
