### ISSUE TITLE
Support Translation Portuguese-Brazil

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Azuriom#290]
### Description of your suggestion

Support Translation Portuguese-Brazil

![image](https://user-images.githubusercontent.com/32937653/216175983-27689e0d-dd6d-4568-a49f-8b46f64a8964.png)

### Advantages

Even though they have no problems using the English version, many users would still like to use their country's language.

**Comment by MrMicky-FR** [comment]
Hello, this is a great suggestion, unfortunately we don’t speak portuguese, but you can contribute to the translations on https://translate.azuriom.com
