### ISSUE TITLE
Allow custom name instead of Minecraft

### ISSUE THREAD

**Issue by Chriskm2001** [Azuriom/Azuriom#292]
### Description of your suggestion

I suggest for adding the feature to turn on and off if minecraft should be the profile, so you can register and change profile picture as well as a custom name, for now it goes by the minecraft Name and skin head

### Advantages

Being able to use custom name on website as well as custom profile picture

**Comment by MrMicky-FR** [comment]
Azuriom is designed to be a game CLS, so using it without a game seems to be little out of scope. Also, Azuriom can already be used with other games, and you can even implement your own games as explained in the [documentation](https://azuriom.com/en/docs/games).

**Comment by Chriskm2001** [comment]
i am using for minecraft, but i just think it could be nice if it was possible to use discord name etc.
