### ISSUE TITLE
Add RSS feed from news

### ISSUE THREAD

**Issue by nolway** [Azuriom/Azuriom#30]
Add RSS feed from news data on /rss route.

**Comment by MrMicky-FR** [comment]
Is there a particular need that requires an RSS feed ? I'm just asking because personally I've never needed an RSS feed.

**Comment by nolway** [comment]
It's for get news on launcher or any kinds of support need it.

**Comment by MrMicky-FR** [comment]
For a launcher you can already get the news with the API on `/api/posts`, it returns the news in JSON and should be a lot easier to parse than XML

**Comment by MrMicky-FR** [comment]
Added with #39 🎉
