### ISSUE TITLE
Verification using Discord

### ISSUE THREAD

**Issue by Jotiprime** [Azuriom/Azuriom#301]
### Description of your suggestion

Now that you added the discord sync option, can you implement the option that users will need to sync discord if not they won’t be able to access the website? To avoid multiple accounts (discord will do the verification) Thanks.

### Advantages

No easy multi accounts will be allowed.

**Comment by MathisDevelopment** [comment]
After, it remains simple to create double Discord accounts

**Comment by JoeDalton9027** [comment]
This function should be activable or not because some creators allowed multi accounts

**Comment by MrMicky-FR** [comment]
This seems out of scope for the Discord bridge and unfortunately wont be an effective way to prevent multi accounts
