### ISSUE TITLE
Remove Azuriom in paypal please put the variable of the page name or something like "Website"

### ISSUE THREAD

**Issue by Jotiprime** [Azuriom/Azuriom#302]
### Description of your suggestion

![Captura de pantalla_20230220_001139](https://user-images.githubusercontent.com/73477224/219981024-a2b86f8e-0010-4470-8978-f22322fd4072.png)

**Comment by MrMicky-FR** [comment]
This was changed in the last update of the shop plugin, make sure you use the last version and that the site name is correctly defined in settings -> global of your admin dashboard
