### ISSUE TITLE
Add expiration date of user verification link

### ISSUE THREAD

**Issue by JoeDalton9027** [Azuriom/Azuriom#307]
### Description of your suggestion

Hello, i think on the mail sent when someone create a account on the website, you shoud tell him that he has 1h to confirm the code, over this, the code will expire and will not function anymore.

You use "timestamp" into the link, why not use it also into the mail :)

Thanks for all

### Advantages

Keep the user informed, and helps to resolve a possible issue if someone tells you that the verification link don't work.

**Comment by MrMicky-FR** [comment]
Added in dc1db8112ae7bf130c09bf88f28defc8a59cf947
