### ISSUE TITLE
Create a plugin to make staff applications inside the website.

### ISSUE THREAD

**Issue by Jotiprime** [Azuriom/Azuriom#308]
### Description of your suggestion

A plugin to make staff applications. Allow to make questions and answers and then send them to the admin dashboards and discord with webhook, like the existing support system but with predefined questions + comments sections to chat with users.

### Advantages

Staff applications integration.

**Comment by MrMicky-FR** [comment]
Unfortunately due to the already huge number of suggestions for Azuriom and existing plugins, we won’t make new plugins. But I agree it would be a great addition if someone with some time makes this plugin 👍
