### ISSUE TITLE
Azuriom for FiveM (STEAM ID)

### ISSUE THREAD

**Issue by ItzT0kyoo** [Azuriom/Azuriom#310]
### Description of your suggestion

Add the STEAMID 64 HEX VERSION for the commands etc... like the steam id 32 on the screen
![Screenshot](https://user-images.githubusercontent.com/126114317/221445702-ce0dbaca-fc88-4a29-8878-c7cd2c4779b1.png)

**Comment by MrMicky-FR** [comment]
It’s `{steam_id}` for the Steam ID 64
