### ISSUE TITLE
Add function to protect images copyrights

### ISSUE THREAD

**Issue by JoeDalton9027** [Azuriom/Azuriom#312]
### Description of your suggestion

This feature would allow you to block the registration of images on the website as well as the shop by right-clicking and then save the image as ... 

This feature would protect servers that create their own images from fraudulent reuse by some malicious users.

### Advantages

This feature would protect servers that create their own images from fraudulent reuse by some malicious users.

**Comment by MrMicky-FR** [comment]
This isn’t possible, as the image MUST be saw by the browser, it will always be possible to download it, even if the right click is blocked (using the browser console for example)
