### ISSUE TITLE
[Theme GUIDE] - Suggestions

### ISSUE THREAD

**Issue by JoeDalton9027** [Azuriom/Azuriom#313]
### Description of your suggestion

Add a way to display trailers on the homepage 
Add some spaces between usefull links buttons. (https://prnt.sc/GzqfsvMaT0UV)
Add some space between singup and singin button (https://prnt.sc/_F0ADUut3sS-)

### Advantages

Allow users to promote one videos for the server, for exemple, this could be add under the discord ID

Improve the visual appearance of the theme.

**Comment by MrMicky-FR** [comment]
This GitHub repo is not for extensions

**Comment by JoeDalton9027** [comment]
Oh sorry, i didn't see it. will post it into the right git repro.
