### ISSUE TITLE
Add the possibility to restrict forums categories to a certain rank

### ISSUE THREAD

**Issue by NoctuaRP** [Azuriom/Azuriom#317]
### Description of your suggestion

For exemple, i own two server : RoleplayA and RoleplayB. I create a categorie for both server on the forum but at a moment i close RoleplayB. 

I can't hide all the RoleplayB forum categorie without delete it.

Please make it possible.

Regards,
Soifox

**Comment by MrMicky-FR** [comment]
Empty categories are now hidden on the homepage in the last forum update (v1.0.14), so restricting all forums in a category will effectively restrict the category
