### ISSUE TITLE
Create a scholarship

### ISSUE THREAD

**Issue by Genetiik93** [Azuriom/Azuriom#319]
### Description of your suggestion

Would it be possible to create a page in which (for a Minecraft server for example), all the items would be listed with their price?

Thus, the staff creates its economy which it displays for the players on its site.
In addition, if ever the economy evolves on the server, the staff could modify the prices of the items and on the page the players would see how many percent the item has evolved.

If a search bar can be added in addition it would be a luxury.

### Advantages

- Players would go to the site more often to check the price of items.
- It would be easier to look at the server economy especially when it evolves.
- The gameplay of the players would be different because some will change their searches according to the request they could observe via this page.

**Comment by MrMicky-FR** [comment]
This can be easily made with a regular page or with the wiki plugin
