### ISSUE TITLE
Dashboard : make stats numbers bigger

### ISSUE THREAD

**Issue by locness3** [Azuriom/Azuriom#32]
The numbers in the stats of the dashboard should be made bigger, they currently are the size of the title of the page which is less important.

**Comment by MrMicky-FR** [comment]
I think it's fine currently, the title is the main text of a page.

**Comment by locness3** [comment]
I don't think so, you come to your dashboard to see how your site's doing, not to know you're on the dashboard

**Comment by locness3** [comment]
I'd recommend watching this video, btw : https://vimeo.com/305601486/a1388ac3a9
