### ISSUE TITLE
Suggestion for the Forum Plugin

### ISSUE THREAD

**Issue by Hartehand** [Azuriom/Azuriom#320]
### Description of your suggestion

My suggestion contains the ability to edit the Color of the symbol for a Forum with the Forum Plugin.

### Advantages

The advantage would be that you could have more freeroam to design your Forum with Color and make it look 
  - B E A U T I F U L L -
 
The alternative would be that you would only be able to edit the title color of a forum and not the symbol color itself.

**Comment by MrMicky-FR** [comment]
Changing color is already possible by using the BBCode editor

**Comment by ShadowFall334** [comment]
I believe that he means the Icons. So that you can change them to an RGB color as you like
