### ISSUE TITLE
Google SSO

### ISSUE THREAD

**Issue by Jotiprime** [Azuriom/Azuriom#324]
### Description of your suggestion

Ass google Sin-On so people can register and login with google.

### Advantages

No need to remember extra password.

**Comment by MrMicky-FR** [comment]
Using Google SSO is usually a bad practice for data privacy, and also currently for all natively supported games you don’t have to remember any additional password for Azuriom:
* For Steam, Minecraft Bedrock Minecraft Online, the Steam/Microsoft login is used so no password is required
* For Minecraft Offline, you can use the AzLink AuthMe integration to use the same password in-game and on the website
