### ISSUE TITLE
Achievements / Badges system

### ISSUE THREAD

**Issue by Casanaura** [Azuriom/Azuriom#326]
### Description of your suggestion

A badges system or achievements system similar to the one "Habbo Hotel" has.
Whenever a user register, purchase an item for the shop and/or any other custom events happen, the user will receive some kind of badge or achievement that can be displayed on the user profiles page (and even on the forum profile for people who bought the plugin)..

The admin can create multiple achievements that can be given manually or automatically if the user meets certain criteria, also add an image to display with a title and description of the badge.

### Advantages

Create a more community like system and invite users to use the website more often.

**Comment by Javdu10** [comment]
I like this idea ! That would fit perfectly in a plugin made by the community,
