### ISSUE TITLE
Discord webhook with changelog plugin

### ISSUE THREAD

**Issue by KingsRequin** [Azuriom/Azuriom#327]
### Description of your suggestion

Everything is in the title, it would be nice to be able to send the changelog on his discord.

### Advantages

The main advantage is a saving of time, not having to send the same message twice.

**Comment by MrMicky-FR** [comment]
Suggestions for the changelog plugin should be on the dedicated GitHub repo: https://github.com/AzuriomCommunity/Plugin-Changelog/issues
