### ISSUE TITLE
Retrieve email during Microsoft login

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/Azuriom#328]
### Description of your suggestion

Hello !

I make this suggestion following a short discussion on the Discord about this, I was wondering what was the point of being able to change one's email from one's profile when Azuriom is used for Minecraft (online), and, it was concluded that it didn't serve much purpose since Microsoft correctly retrieves the email.

My suggestion would be:
- Would it be possible to completely disable/add an option in the admin panel to disable the function to change one's email ?

### Advantages

This would prevent players from doing something that serves no purpose and thus make the CMS even easier to use without adding that little unnecessary layer.

**Comment by MrMicky-FR** [comment]
The ability to set an email in the profile shouldn’t be removed (email are used for shop confirmations and other important information), but instead try to automatically get the email address from the Microsoft account

**Comment by MrMicky-FR** [comment]
After some consideration, this won't be implemented, as the e-mail address is a personal data, so collection would require explicit user consent and an option to login without sharing email address, which isn't possible without adding adding one more step before login (this step would be a lost of time to all users who are already registered)
