### ISSUE TITLE
Add a form system.

### ISSUE THREAD

**Issue by LesConseilers** [Azuriom/Azuriom#329]
### Description of your suggestion

Hello, I propose here a way to make a page with a possibility to make forms fillable by everyone. 
There could be 4 types of responses: 
- Text
- Multiple choice
- Single choice
- File

Also, when someone fills out a form, there could be a mention on Discord
Finally, there could be a small parameter that, depending on the answer, leads to another question.

### Advantages

Allows recruitment (especially for moderation) / Satisfaction survey directly via the website.

**Comment by MrMicky-FR** [comment]
Unfortunately due to the already huge number of suggestions for Azuriom and existing plugins (~50 open issues across the https://github.com/Azuriom organization, and it keeps growing), we won’t make new plugins. But I agree it would be a great addition if someone with some time makes this plugin 👍
