### ISSUE TITLE
Server setup errors

### ISSUE THREAD

**Issue by Xonbie** [Azuriom/Azuriom#33]
Getting " The connection to the server has failed, the address and/or port are incorrect, or the port is closed." error message when using verify connection button. Ports are open and address is correct.

When saved server is online and player count is correct. Have attached screenshot 

![image](https://user-images.githubusercontent.com/7809451/91191332-ff42b200-e737-11ea-9aac-0b3c52b04da6.png)

Server always shows status as offline on initial creation until config is saved. Screenshot attached

![image](https://user-images.githubusercontent.com/7809451/91192884-cf94a980-e739-11ea-8034-f6e2f9a0dc26.png)

**Comment by SkyWarZzeur** [comment]
hello, if you need support pls join our discord: https://azuriom.com/discord
