### ISSUE TITLE
Conflict with Player Analitics (Plan) plugin

### ISSUE THREAD

**Issue by danielgabrielyan127** [Azuriom/Azuriom#332]
### Bug description

Hello. When I enable the Plan plugin on any of my servers, my site's admin panel crashes with error 500 Internal Server

### Step to reproduce

1. Installing Plan on my Velocity server and turn on Webserver
2. Connecting Velocity plan to MySQL DB
3. Installing Plan on bukkit server and turn off webserver (wiki information of plan plugin)
4. Connecting Plan to DB
5. Get crash on admin panel with 500 Internal error
6. If I disable the plan plugin, the admin panel starts working

### Errors / Logs

No logs related to admin panel crash

### Web server

Nginx

### Database type

MySQL

### PHP version

8,1

**Comment by MrMicky-FR** [comment]
Please send the logs, and if no logs are created this might be a files permission issue on your website.
