### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by DrTableBasse** [Azuriom/Azuriom#335]
### Description of your suggestion

I think it should be a good idea if you propose a roadmap of your project because people will know which fonction will be do etc...

### Advantages

it's cool !

**Comment by MrMicky-FR** [comment]
We don’t have a specific roadmap for the current Azuriom version, as we are mostly implementing GitHub features requests. For the next big release, you can see the planned features on https://github.com/orgs/Azuriom/projects/2 (but might not always be up-to-date)
