### ISSUE TITLE
Extra information for wiki-pages

### ISSUE THREAD

**Issue by Casanaura** [Azuriom/Azuriom#336]
### Description of your suggestion

At the bottom of every article page from the wiki, add "Latest update by (user whom updated it) at (date).
heres an example of what i mean: 

https://i.imgur.com/iP2lJuE.png
![iP2lJuE](https://github.com/Azuriom/Azuriom/assets/128449567/f68a51bd-7770-4b7b-a2d4-911dc1698003)

### Advantages

Get to know the latest update from an article and whom updated it.

**Comment by MrMicky-FR** [comment]
This repository isn’t for plugins, and can already add this in the page content if you want
