### ISSUE TITLE
Support `minecraft` protocol in URL

### ISSUE THREAD

**Issue by ZoumiSurGithub** [Azuriom/Azuriom#340]
### Description of your suggestion

Be able to put a link like: **minecraft://?addExternalServer=§7Moon§eight|moonlight-mcbe.fr:19132/** on the servers parameter.
![image](https://github.com/Azuriom/Azuriom/assets/85941634/262892d7-fdb9-4bdc-9987-5d267808f42b)

### Advantages

When players want to join the server, they can add the server directly via this link while opening their game on any platform.

**Comment by MrDoudou** [comment]
PR: https://github.com/Azuriom/Azuriom/pull/341

**Comment by MrMicky-FR** [comment]
Added support to specifying protocols in Laravel in https://github.com/laravel/framework/pull/47843, and prepared in Azuriom through 5f67ce85e1712868169782f90e609f422e4ca903, so this will be available in Azuriom immediately after we update our Laravel version
