### ISSUE TITLE
Add clickable links to logs

### ISSUE THREAD

**Issue by MrDoudou** [Azuriom/Azuriom#343]
### Description of your suggestion

Azuriom currently uses #{ID} to display logs. It would be a good idea to add the user's username and make it clickable to the user's profile.

<img width="1073" alt="CleanShot 2023-06-04 at 17 00 00@2x" src="https://github.com/Azuriom/Azuriom/assets/22004704/d9e8f060-ba5b-45c0-9f5b-d626a3f03a57">
 

### Advantages

Enhanced user experience

**Comment by didi955** [comment]
Already implemented 

![Capture d'écran 2023-06-07 215423](https://github.com/Azuriom/Azuriom/assets/45293702/c3071f05-8937-4c19-bc63-59e7b9c3f671)

**Comment by MrMicky-FR** [comment]
Closing at it's already implemented as said above :)
