### ISSUE TITLE
Why you can add an email when Azuriom is set up to use Steam (Fivem)

### ISSUE THREAD

**Issue by Joti-prime** [Azuriom/Azuriom#349]
### Bug description

You have the option to add your email in your profile but doesn't work (500 error) because the website is set up to use Fivem (Steam) 
![image](https://github.com/Azuriom/Azuriom/assets/127934270/763fc5c5-d36f-4d2b-a78c-ac664143b7d6)
![image](https://github.com/Azuriom/Azuriom/assets/127934270/8e47c35b-a10b-448c-b95f-6c182b980da9)

### Step to reproduce

Go to your profile. 

### Database type

MySQL

### PHP version

8-.2

### Additional context

Remove that part (email) when setting up with Fivem.

**Comment by MrMicky-FR** [comment]
The e-mail setting is expected to be available on FiveM setup, as the e-mail address may be used to send e-mail like shop invoices or support reply notification.

About your issue it’s most likely an issue with your e-mail setup, you can check in the admin dashboard, settings -> mail
