### ISSUE TITLE
Error 500 when uploading any image.

### ISSUE THREAD

**Issue by riiz0r** [Azuriom/Azuriom#35]
When ever I try to add my logo it gives me a 500 Server Error.
<img width="1060" alt="Screen Shot 2020-09-13 at 2 21 04 PM" src="https://user-images.githubusercontent.com/68617740/93026554-5ec00f00-f5cc-11ea-89d0-020d3c20a258.png">

**Comment by MrMicky-FR** [comment]
Do you have the `fileinfo` extension enabled ? It should be enabled by default, but if it is not, try to enable it to see if the problem still occurs.

**Comment by riiz0r** [comment]
Okay, I will try that

**Comment by riiz0r** [comment]
It wasn't installed, but now I have installed it and it now works. Thank you!
