### ISSUE TITLE
Improvements to member profiles (Social Networks)

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Azuriom#351]
### Description of your suggestion

Currently when we click to see the profile it shows our information, SteamID, Money, when it was registered.

![image](https://github.com/Azuriom/Azuriom/assets/32937653/194e6fab-18ba-4cf2-aef6-cd4b78fe390b)

I thought if it would be possible to make the options to show the SteamID a link, when the user clicks it opens his steam profile.

User option to also register their social networks, such as Discord, Twitter, Instagram, Twitch.TV, Youtube, Facebook and other social networks. And all that the user puts become a clickable link, for other users to open if they want.

In theory it would be to improve his profile, create a biography, equipment he uses and such.

**Comment by MrMicky-FR** [comment]
Hi, this is already implemented in the forum plugin :)
