### ISSUE TITLE
Mail customization

### ISSUE THREAD

**Issue by xlanyleeet** [Azuriom/Azuriom#354]
### Description of your suggestion

I suggest customizing email notifications, starting at least with the choice of colors for the background, because I don't really want to see white at night))

### Advantages

![image](https://github.com/Azuriom/Azuriom/assets/61755593/14854c81-460e-4bc8-b32f-6746ed742064)

**Comment by Javdu10** [comment]
Hello, all of this is achievable with a custom theme, you can look at such tutorials : https://medium.com/@christianjombo/customizing-laravels-default-notification-email-template-adding-a-logo-and-changing-ff6f107dd640

Then using your knowledge about Azuriom themes override the views responsible for the default laravel mail messages
