### ISSUE TITLE
Add an option to force https

### ISSUE THREAD

**Issue by GaspardG0001** [Azuriom/Azuriom#355]
### Description of your suggestion

I suggest adding an option in the CMS parameters to force https, as you can do today by modifying the `.htaccess` file.

### Advantages

Compared to the current way of forcing https, this would already help people who have difficulty manipulating files. It would also prevent forced https from being disabled every time Azuriom is updated.

**Comment by MrMicky-FR** [comment]
I think this is out of the scope of a web application, this kind of redirections should be made on the webserver or even before on the proxy if there is one.
