### ISSUE TITLE
Textarea Hidden

### ISSUE THREAD

**Issue by BaptGosse** [Azuriom/Azuriom#357]
### Bug description

all textarea have the parameter style="visibility: hidden" which makes it impossible to put text in the admin panel as for maintenance or to create an article

### Step to reproduce

Have Azuriom version 1.1.1
Write an article

### Web server

Nginx

### Database type

MariaDB

### PHP version

8.2

**Comment by MrMicky-FR** [comment]
This isn’t added by Azuriom: https://github.com/search?q=repo%3AAzuriom%2FAzuriom+visibility&type=code

I tested on both local setup and on the [demo](https://demo.azuriom.com/) and I don’t have the issue. Can you try on a different website and with a different browser ?

**Comment by BaptGosse** [comment]
It's good, clear just your cache
