### ISSUE TITLE
Add Google sing in

### ISSUE THREAD

**Issue by joti-prime** [Azuriom/Azuriom#358]
### Description of your suggestion

Will be good to have google Sing in in the next update. Google

### Advantages

People don't need to remember more passwords, more secure.

**Comment by naekaa444** [comment]
I've already made the proposal and it was refused.
Google privacy really sucks.

I've made a GoogleAuth plugin that's available on my GitHub if you're interested anyway.

**Comment by MrMicky-FR** [comment]
Duplicate of #324, which seems to be your own suggestion !??
