### ISSUE TITLE
Ajouter un système de chat de proximité via le site et le plugin

### ISSUE THREAD

**Issue by NeXoS-20** [Azuriom/Azuriom#359]
### Description of your suggestion

Ajouter une option de chat de proximité via le site pour parler avec les autres joueurs directement sur le site sans installer de logiciel

### Advantages

Bah ça peut être cool

**Comment by MrMicky-FR** [comment]
C’est une bonne idée mais ça serait plus adapté dans un plugin Azuriom que directement intégré à Azuriom

**Comment by NeXoS-20** [comment]
Possible d'avoir une personne qui pourrait le faire bénévolement et le mettre en ligne car je suis a sec
