### ISSUE TITLE
Can't add content to an article.

### ISSUE THREAD

**Issue by BearlessYT** [Azuriom/Azuriom#360]
### Bug description

When we want to create an article we have to add The name, the url, the desription and the content. And when we have to write the content we can't because the "bubble" for the content disapear when the page is loaded and we can't write.

### Step to reproduce

Create an article and see

### Database type

None

### PHP version

8.1

**Comment by naekaa444** [comment]
Clear your browser cache

**Comment by MrMicky-FR** [comment]
As suggested by naekaa444, clearing your browser cache should solve the issue
