### ISSUE TITLE
If I remove a role in the website it doesn't remove it in Discord

### ISSUE THREAD

**Issue by joti-prime** [Azuriom/Azuriom#362]
### Bug description

Using the Discord Linked roles, when I remove a role in the website (azuriom) it doesn't in discord. I remember that this was working with the beta of the plugin, I don't know if discord added some extra option to allow this. Discord

### Step to reproduce

Just remove a role in the website and if user had that role in discord will keep having that role. the 

### Database type

None

**Comment by MrMicky-FR** [comment]
Hi, do you have any information on how to reproduce this issue ? Because I've just tested (again) and it works fine

**Comment by joti-prime** [comment]
I have already seen the problem, the problem has been when switching from the old method (for GitHub sponsors the beta of the plugin) to the new one, that all the bug roles have remained, that is, until the users link their discord again with the web, even if the user deletes them or their role changes, they will continue to have it.

Can you make a plugin or something so that all the roles are unlinked?

**Comment by MrMicky-FR** [comment]
The method used is exactly the same as during the beta, and I tested on multiples sites and it works for me. How are you changing role? In the admin panel

**Comment by joti-prime** [comment]
Now I'm using the new integrated method so, because the callback link is different I think that it breaks.

**Comment by MrMicky-FR** [comment]
Make sure to update the callback link on Discord dashboard

**Comment by joti-prime** [comment]
Works it works, the problem is that when I deleted the old plugin, the roles in discord have been maintained, so, until people link their discord account again, they will not connect again, therefore, people will continue to have the same role even if they delete their account.

**Comment by MrMicky-FR** [comment]
Hi, thanks for your patience, I understand the issue now. 

To migrate the data from the beta plugin to the new integrated system, you can run the following SQL query in your database :
```sql
INSERT INTO discord_account (name, user_id, discord_user_id, access_token, refresh_token, expires_at, created_at, updated_at)
SELECT name, user_id, discord_user, access_token, refresh_token, expires_at, created_at, updated_at
FROM discord_users;
```
