### ISSUE TITLE
Impossible de s'inscrire en custom game

### ISSUE THREAD

**Issue by naekaa444** [Azuriom/Azuriom#366]
### Bug description

Hello, depuis la nouvelle version il est impossible de s'inscrire lorsqu'on est en custom game. 

Chaque tentative d'inscription met toujours l'erreur : "The name must be a valid None username." même si le pseudo est valide. 

J'ai effectué des tests et selon mes observations, cette problématique pourrait éventuellement venir du fichier "Rules/GameAuth.php". (à confirmer)

### Step to reproduce

Installer Azuriom en choisissant Custom Game et essayer de s'inscrire avec un pseudo valide.

### Web server

Apache

### Database type

MySQL

### PHP version

8.1

**Comment by MrMicky-FR** [comment]
Le problème vient du plugin du jeu custom en question. Également Azuriom n’est pas prévu pour fonctionner sans aucun jeu
