### ISSUE TITLE
Un fonction pour dire quel grade corresponds a quel grade discord et forcer le login avec discord et voir dans le panneau admin dans utilisateurs avoir une option trier par... et ajouter des thèmes admin et des addons admins

### ISSUE THREAD

**Issue by NeXoS-20** [Azuriom/Azuriom#368]
### Description of your suggestion

Lire le titre
Trier par
- Link via discord
-  Mail verifiée
...

### Advantages

Grades syncronisés
Connexion discord
Symple a gérer
Plus beau + de fonctions

**Comment by NeXoS-20** [comment]
Mais avec l'id du role et pour le panel admin il y a juste a supprimer le fichier

**Comment by NeXoS-20** [comment]
Et les addons admins genre un staff chat, un calendrier, une liste de choses a faire sur le panel admin via des plugins admin

**Comment by MrMicky-FR** [comment]
> Et les addons admins genre un staff chat, un calendrier, une liste de choses a faire sur le panel admin via des plugins admin

C’est des idées de plugin directement, rien de spécifique à ce niveau là
