### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by MaXx-62** [Azuriom/Azuriom#369]
### Description of your suggestion

Pouvoir choisir le nombre de crédits qu'on veux aux lieu de faire des pré reglages de credits

et cela converti automatiquement en argent

![image](https://github.com/Azuriom/Azuriom/assets/4140252/9aaef3a6-9756-4e45-bf84-2f4d8b50defb)
![image](https://github.com/Azuriom/Azuriom/assets/4140252/4bde2737-7fe5-4ad6-b4b6-304ae074e7e4)

Voici des screens pour mieux comprendre

Bonus : Ajouter une option "minimum de credit que les gens peuvent mettre"

### Advantages

L'avantage est que les gens peuvent s'en servir aussi comme système de donation

**Comment by MrMicky-FR** [comment]
Dans ce cas pourquoi utiliser le système de crédits ?

**Comment by MaXx-62** [comment]
> Dans ce cas pourquoi utiliser le système de crédits ?

Parce que au moins les gens peuvent garder des crédits comme un porte monnaie, et aussi le système de crédit est bien, pour des giveaways par exemple :)
