### ISSUE TITLE
Project Zomboid RCON support

### ISSUE THREAD

**Issue by Maverick0581** [Azuriom/Azuriom#371]
### Description of your suggestion

Hey, I'm currently a Project Zomboid server owner and I'm using Azuriom with the Rust configuration. The problem is that Rust RCON obviously don't work with Project Zomboid one, everything works fine except the RCON.

If you could add a Project Zomboid support, that would be awesome !
Thanks

**Comment by MrMicky-FR** [comment]
You can try with a more generic Steam configuration for Azuriom, like GMod or CS:GO, but otherwise we are not planning to support more games natively in Azuriom. However it’s also possible to create a custom game yourself, see the documentation https://azuriom.com/en/docs/games
