### ISSUE TITLE
Error 500 when using Microsoft connexion 

### ISSUE THREAD

**Issue by Marssouss** [Azuriom/Azuriom#373]
### Bug description

Hello,

I'm no longer able to log in to Azurium using the Microsoft login. After completing the login step, I encounter a 500 error.

I haven't made any changes since, so I'm unsure of what could have happened.

Do you have any ideas or suggestions to explore in order to resolve the issue?

Thank you, have a good day.

### Step to reproduce

The bug occurs every time I log in, no matter which account is used.

### Web server

Apache

### Database type

MariaDB

### PHP version

Php 8.1.2

**Comment by MrMicky-FR** [comment]
Hello, this issue is because Mojang blocked our API key, we are currently in contact with them and waiting for reactivation, which should took few days. Until then, you can get API keys on https://dev.azure.com/microsoft/ and put them in the `.env` file

**Comment by Marssouss** [comment]
Hello, thank you for this response. Indeed, I was able to see on Discord that the issue was recurring.
I have a question regarding the Microsoft Azure API key to be placed in the .env file.
- I couldn't figure out which variable to add it to.
- The CMS is deployed on a Linux machine, not hosted on Microsoft Azure. In my opinion, the API key would allow an application deployed on Azure to be authorized. Is that correct?
Thanks again for your quick response.

**Comment by BaptGosse** [comment]
How can i get API keys on https://dev.azure.com/microsoft/

**Comment by Marssouss** [comment]
I d'ont know :/

If you found this, i'm interested by the response :D

**Comment by MrMicky-FR** [comment]
The issue is now solved :)
