### ISSUE TITLE
All password have to be reset after the latest update

### ISSUE THREAD

**Issue by dikovmaxim** [Azuriom/Azuriom#374]
### Bug description

I recentrly updated the Azuriom on my minecraft projectm but every user gets a message, that the password should be reset before continuing. It looks like this is a new feature, wich i cannot disable, bacause i lost the access to the admin panel. (No verification email is possible), Maybeit is because of hashing, but I am really afraid to manipulate the database, because it is binded to Authme. Sorry for posting it as a bug issue, i haven't find any information online.

### Step to reproduce

Just update the Azuriom.

### Errors / Logs

Чтобы продолжить, необходимо сбросить пароль.
To continue, you have to reset the password. 

### Web server

Nginx

### Database type

MySQL

### PHP version

8.1.21

**Comment by MrMicky-FR** [comment]
This is most likely caused by a problem during the update, because just updating Azuriom won’t cause this issue.

Could you try doing the command `php artisan migrate --force` or try going on the URL /admin/settings/migrate of your website ?

**Comment by qwlke** [comment]
"try going on the URL /admin/settings/migrate of your website" - redirects to login.

**Comment by qwlke** [comment]
The issue is resolved, this command helped: "php artisan migrate --force".

**Comment by aws0jam** [comment]
Hello! How can I use this command in cpanel? Because i have same issue

**Comment by MrMicky-FR** [comment]
Try executing these commands in PhpMyAdmin
```sql
ALTER TABLE `users` ADD `password_changed_at` TIMESTAMP NULL AFTER `last_login_at`;
UPDATE `users` SET `password_changed_at`=`created_at`;
INSERT INTO `migrations`(`migration`, `batch`) VALUES ('2023_06_03_add_password_changed_at_to_users_table', 0);
```

**Comment by aws0jam** [comment]
![image](https://github.com/Azuriom/Azuriom/assets/35460228/6886435b-b3dd-4587-825b-ea387d25914d)
Not working said duplicated

**Comment by MrMicky-FR** [comment]
Try executing only the two last lines without the first one

**Comment by aws0jam** [comment]
this command update password_changed_at table to creation date right ? Becouse do nothing 
![image](https://github.com/Azuriom/Azuriom/assets/35460228/90a56d56-db99-4ca5-9d34-0e71efab8561)

**Comment by MrMicky-FR** [comment]
Yes, but when the value of this column is not not null, it wont ask to reset password

**Comment by aws0jam** [comment]
![image](https://github.com/Azuriom/Azuriom/assets/35460228/e945a5e8-c442-4ca2-afd6-c287f95a0381)

**Comment by aws0jam** [comment]
solved idk how ....
