### ISSUE TITLE
Permettre de ping dans le embed pour les news

### ISSUE THREAD

**Issue by NeXoS-20** [Azuriom/Azuriom#378]
### Description of your suggestion

Pouvoir choisir pour ping un rôle spécial avec le webhook dans les paramètres généraux et pour faire la liaison avec discord pour les grades facilement et ajouter une option pour forcer la connexion à discord 

### Advantages

Pouvoir mieux avertir ma commu et pouvoir automatiquement mettre les grades aux membrs et qu'ils soient automatiquement liés

**Comment by MrMicky-FR** [comment]
Déjà possible de ping dans le message dans l’embed
