### ISSUE TITLE
Discord Role Link

### ISSUE THREAD

**Issue by MaximusMcfly** [Azuriom/Azuriom#382]
### Description of your suggestion

So, Discord is rolling out this new role linking system, i think you could implement it and also add authentication through Discord or make it so that you could link your Discord account to the CMS. [And ofcourse make it optional.]
Links:
[Discord role linking](https://support.discord.com/hc/en-us/articles/8063233404823)
[Admins: Discord role linking](https://support.discord.com/hc/en-us/articles/10388356626711)

### Advantages

The CMS will have a tighter bond with Discord if enabled in settings.

**Comment by crashzk** [comment]
@MaximusMcfly already has this function since version **1.1.0** of Azuriom.

**Comment by crashzk** [comment]
Admin Panel -> Roles
![image](https://github.com/Azuriom/Azuriom/assets/32937653/327d5c16-b883-4e33-bd54-e667cb8d66a8)

Then just configure it as requested.
