### ISSUE TITLE
Not all bootstrap icons work

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Azuriom#383]
### Bug description

I tested these icons in the navigation bar and it just doesn't work.

https://icons.getbootstrap.com/icons/person-standing/
https://icons.getbootstrap.com/icons/person-raised-hand/

![image](https://github.com/Azuriom/Azuriom/assets/32937653/72110750-a3f6-4ff2-b76e-a500c82be13b)

### Step to reproduce

Configure any of these icons in the navigation bar and you will see that it does not work.

### Errors / Logs

[laravel-2023-09-12.log](https://github.com/Azuriom/Azuriom/files/12589857/laravel-2023-09-12.log)

### Web server

Apache, Nginx

### Database type

MariaDB

### PHP version

8.1

### Additional context

I don't know if it would be something in Azuriom or Bootstrap. 

In this case, I only tested these icons, I would have to see if there are more.

**Comment by MrMicky-FR** [comment]
Some patience please… These icons was added in Bootstrap Icons [4 hours ago](https://github.com/twbs/icons/releases/tag/v1.11.0), they all will be available in the next Azuriom release

**Comment by crashzk** [comment]
Sorry, I didn't really see this release, in this case I went to their website and only saw the icon and wanted to use it, anyway, thank you.

**Comment by MrMicky-FR** [comment]
Updated in last Azuriom release :)
