### ISSUE TITLE
`General -> Upload` support for rich text editor

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Azuriom#394]
### Description of your suggestion

I noticed that in most of Azuriom the rich text editor has the option to add an image to the text, but there would be no option to upload it.

![image](https://github.com/Azuriom/Azuriom/assets/32937653/c0526cc1-146b-4a70-853d-bdf3102071b3)

However, in the WiKi plugin this option is active: https://github.com/Azuriom/Plugin-Wiki/commit/90c25e5bff501986b303bf3264def2622cb149f4

![image](https://github.com/Azuriom/Azuriom/assets/32937653/8743bca6-f1be-42a6-85c5-87e9f154d518)

Would this feature be possible to implement across Azuriom itself?

**Comment by MrMicky-FR** [comment]
It’s already implemented in most rich-text areas (pages, posts and in many plugins) but it’s not possible to just add it on all areas automatically as we need to track the uploaded images so the unused ones (removed from text or if the associated page/post/etc is deleted). 

When it’s not implemented you can upload it through the « Images » tab of the admin panel
