### ISSUE TITLE
Displaying purchases if the profile

### ISSUE THREAD

**Issue by AceCookies** [Azuriom/Azuriom#397]
### Description of your suggestion

Add a list of products a user has purchased to thier profile page.

### Advantages

Users can track thier spending.
It could even create a discount system for a certain number of purchases/money spent.

**Comment by MrMicky-FR** [comment]
Already supported:
![image](https://github.com/Azuriom/Azuriom/assets/30863452/0f580e53-f5bc-42b6-acb7-576b52c90790)
