### ISSUE TITLE
Adding notifications on Telegram

### ISSUE THREAD

**Issue by xlanyleeet** [Azuriom/Azuriom#399]
### Description of your suggestion

Hello, azuriom already has server integration and notifications in the form of webhooks. Why not do the same with Telegram? At least notifications about news, purchases and the like.

**Comment by MrMicky-FR** [comment]
AFAIK, Telegram doesn’t support basic Webhooks like Discord, and also Telegram usage is pretty low in the gaming community so I’m not sure if it would be worth the effort.

But of course this can be implemented pretty easily as an Azuriom plugin (the longest part would be to interact with the Telegram API)
