### ISSUE TITLE
Azboost turned on in a subfolder breaks homepage

### ISSUE THREAD

**Issue by aidanellyer** [Azuriom/Azuriom#40]
![image](https://user-images.githubusercontent.com/11576326/95566296-456a8100-0a19-11eb-878f-7a020ff9dcf3.png)
This is what I saw when I turned on azboost. I have my forums in a subfolder called /home/ this only happened to the home page

**Comment by MrMicky-FR** [comment]
Do you have the same problem if you disable AzBoost ?

**Comment by aidanellyer** [comment]
> 
> 
> Do you have the same problem if you disable AzBoost ?

No, disabling azBoost fixed the issue.

**Comment by MrMicky-FR** [comment]
Unfortunately I can’t reproduce this issue, if you still have this problem please join our [Discord server](https://azuriom.com/discord) as it would easier to solve this 😀
