### ISSUE TITLE
Unturned support

### ISSUE THREAD

**Issue by naverek** [Azuriom/Azuriom#400]
### Description of your suggestion

I know that everyone can make own custom connection but no everyone know how to do this. That is the good reason to add it. Maybe if someone have it already (unturned connection) done just share your code here and maybe who know the person that need it will use it. Thank you for your reply.

**Comment by gru2007** [comment]
Does it use a Steam Query protocol? If so, it’s easy to create basic support.

For example I have written support for Arma3 for my own purposes

**Comment by naverek** [comment]
> Does it use a Steam Query protocol? If so, it’s easy to create basic support.
> 
> For example I have written support for Arma3 for my own purposes

I think that unturned have a query protocol but I’m not sure. I will check it. Can u help me with creating this for unturned? I would be grateful. This is my discord for faster contact: gildiabee
