### ISSUE TITLE
Configurable image proxy for Markdown

### ISSUE THREAD

**Issue by cg0** [Azuriom/Azuriom#403]
### Bug description

For some users attempting to access an embedded image external to the hosted instance they will receive a 404 from images.webserv.nl instead of the actual image.

Removing the code from the instance that marks images as external allowing the image to be embedded directly fixes this issue

While I'm aware this is an issue with a third party service the ability to disable this integration would be handy

### Step to reproduce

Via an external plugin an Imgur image is added to content, Azuriom detects it as an external image and prefixes it with https://images.weserv.nl/?URL and a 404 is given to the client

### Errors / Logs

There are no error logs given serverside

### Web server

Nginx

### Database type

MariaDB

### Additional context

In the limited test we had three users on three different UK ISPS, out of the three only one could load the image until the next day where it loaded for 2/3

**Comment by MrMicky-FR** [comment]
Just for context, we use this service to add a security layer to users images, like preventing IP address leaking.

But yes I agree it should definitely be configurable easily !
