### ISSUE TITLE
add placefolder {current_year} for copyright

### ISSUE THREAD

**Issue by xlanyleeet** [Azuriom/Azuriom#407]
### Description of your suggestion

To avoid constantly changing the year digit, I suggest adding a placeholder example:
`2019-{current_year} your.mcserver.net`
> 2019-2023 your.mcserver.net

**Comment by MrMicky-FR** [comment]
This is a great idea but unfortunately due to the way it’s currently implemented, it’s not possible without requiring modifications from all theme, which would be too complicated 😕
