### ISSUE TITLE
After a registration, password needs to be reset, even if I try to log in with the wrong one

### ISSUE THREAD

**Issue by dikovmaxim** [Azuriom/Azuriom#413]
### Bug description

I recently already asked about a similar issue
Suddenly all users, who joined our minecaft server and created an account using authme coud not log in to Azuriom, and everyone started so get messages about the password needs to be reset. Earlier it was no problem, but sudenly it became one. We made sure everyting is up to date and did everyting suggested in my previous similar issue https://github.com/Azuriom/Azuriom/issues/374, migration etc, but nothing helped

### Step to reproduce

Unfortinatly no steps. I was just informed that this bug suddently occured
We did not update neither any plugins, nor azuorium before that

### Web server

Nginx

### Database type

MariaDB

### PHP version

8.1.21

**Comment by MrMicky-FR** [comment]
Which AuthMe integration are you using ? AzLink or the Azuriom AuthMe plugin?

**Comment by dikovmaxim** [comment]
We use custom authme wich ist just configured to use propper database table, columns and hashing methids. We have Azlink installed thou

**Comment by MrMicky-FR** [comment]
In this case you need your custom AuthMe to fill the column `password_changed_at` with the current date in the `users` table, when creating a new account
