### ISSUE TITLE
Reimagened update section

### ISSUE THREAD

**Issue by xlanyleeet** [Azuriom/Azuriom#417]
### Description of your suggestion

Currently, the Updates tab contains only a button to check for updates and the CMS version itself, and there was an idea to add an embedded list of updates, but it didn't work out.

Suggestion:
Make this tab more informative, with information about the system and the php version. And an update block that would contain changes in the new version of the CMS and buttons to update and skip the version (with a warning, of course).

**Comment by MrMicky-FR** [comment]
There is already a link to the GitHub releases pages with detailed changelog about all versions, and it’s always recommended to update to the last Azuriom version so we are not going to encourage skipping an update, this would only cause more support requests
