### ISSUE TITLE
Improve Money Transfer

### ISSUE THREAD

**Issue by xlanyleeet** [Azuriom/Azuriom#418]
### Description of your suggestion

There is a money transfer function, and I would like to see in my payments or in another tab to whom and how much I have transferred. And it would be possible to add a commission system where the administrator sets the appropriate percentage and it is displayed in the window before the transfer.

**Comment by MrMicky-FR** [comment]
Money transfers are a built-in function of Azuriom, so logging them into the shop payments wouldn't make sense. But they are already logs in the "Logs" tab of the admin dashboard:
<img width="1197" alt="image" src="https://github.com/Azuriom/Azuriom/assets/30863452/e3745ce3-675d-443c-a539-699f0650bab0">

And it also appears on the user edition page:
<img width="1208" alt="image" src="https://github.com/Azuriom/Azuriom/assets/30863452/121cc6d4-7838-4491-9a56-c499b7de9581">

For commission and more fine-tuned customization, selling giftcards might be a better solution
