### ISSUE TITLE
Add API endpoint to list linked servers

### ISSUE THREAD

**Issue by GeekCornerGH** [Azuriom/Azuriom#423]
### Description of your suggestion

I'd like to see an endpoint on the api which can return the list of linked servers (ping and so on) for use in some cases where using an API like mcsrvstat.us isn't possible (firewalled bungeecord backend servers for example).

The api result may look like this for example:
```json
[{
  "name": "Server A",
  "online": true,
  "players": {
    "online": 42,
    "max": 42
  }
},
{
  "name": "Server B",
  "online": false
}]
```

**Comment by Javdu10** [comment]
Hello, 

I think it would be best if you try to implement this feature in a custom plugin, this way you could add any other requirements you might have to suit your needs

**Comment by MrMicky-FR** [comment]
Already available on `/api/servers` ;)

**Comment by GeekCornerGH** [comment]
Thanks, I missed that
