### ISSUE TITLE
possibility of including "user tags" when creating a page

### ISSUE THREAD

**Issue by anthogame** [Azuriom/Azuriom#431]
### Description of your suggestion

Hi,
it would be handy to be able to include tags in the pages you 
created. Tags like {users->name} {users->money} {money} {site_name} this would make more complete pages

### Advantages

greater flexibility and customization

**Comment by MrMicky-FR** [comment]
How it should be handled when a user visits the page without being logged in ?

**Comment by anthogame** [comment]
In this case we can block the page at grades, it's simple.

We can also ensure that the pages calling for this information are only accessible if the player is online. Otherwise, we redirect it on connection

**Comment by MrMicky-FR** [comment]
For `{site_name}` it seems a little over-engineered as most likely it won't change often.

For the other placeholders, I agree it can be useful, but to add them to Azuriom would require modifying a lot of existing themes, which would be quite complex. But as a solution, you can easily add them by replacing this line (in `resources/views/pages/show.blade.php`):
https://github.com/Azuriom/Azuriom/blob/ef9755f238b213d48759d86f4ff57d231af5b2cc/resources/views/pages/show.blade.php#L11
With:
```blade
@auth
    {!! str_replace(['{money}', '{name}'], [auth()->user()->money, auth()->user()->name]) !!}
@else
    {!! $page->content !!}
@endauth
```
