### ISSUE TITLE
possibility of adding several links to a navbar menu

### ISSUE THREAD

**Issue by anthogame** [Azuriom/Azuriom#432]
### Description of your suggestion

Hi,

have the possibility of adding second links to the navbar menus (second link necessarily opening a new tab) this would allow in certain cases to redirect to the desired page and automatically open the associated FAQ for example

### Advantages

navigation comfort for users
For a user Friendly experience

**Comment by MrMicky-FR** [comment]
I am not sure to understand, you can already add multiple links to a navbar menu ?

**Comment by anthogame** [comment]
here is a screen of what I am talking about, possibility of adding a link opening in a new additional tab
![navbar](https://github.com/Azuriom/Azuriom/assets/37049843/5f978ecf-7223-4a90-9ccd-cb0f5a02be9c)

**Comment by MrMicky-FR** [comment]
I’m still not sure to understand as it’s already possible to open the link in a new tab?
