### ISSUE TITLE
Add more then one role to a user

### ISSUE THREAD

**Issue by Nu11ified** [Azuriom/Azuriom#433]
### Description of your suggestion

Is there a possibility to add a way for a person to have their main role, and then multiple sub roles? Similar to zenforo’s user group and then secondary groups. 

### Advantages

Allows for people for example who have a admin title but are also donators to have both under their profile. It would also make plugins easier to create when the use case requires more information on the user.

**Comment by MrMicky-FR** [comment]
Unfortunately it would be too complex to implement due to the current database structure and would require modifying most of the themes/plugins
