### ISSUE TITLE
Marked as verified email without ever verifying the email

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Azuriom#434]
### Bug description

I did a clean installation of Azuriom and informed my Steam during the installation to be admin master.

Once the installation was complete, I noticed that my user has a verified email even though I have never checked my email or activated the email system yet.

![image](https://github.com/Azuriom/Azuriom/assets/32937653/93fe9526-5f41-4f21-b5ca-558260211e3d)

![image](https://github.com/Azuriom/Azuriom/assets/32937653/9caba44b-026e-48df-8cb4-ca54aaa563a8)

![image](https://github.com/Azuriom/Azuriom/assets/32937653/aa23c71c-e8b5-43d0-aa93-2a88d822efa4)

### Step to reproduce

Just a clean install, from scratch.

### Errors / Logs

[laravel-2024-03-28.log](https://github.com/Azuriom/Azuriom/files/14796665/laravel-2024-03-28.log)

### Web server

Apache, Nginx

### Database type

MariaDB

### PHP version

PHP 8.2 (ea-php82)

**Comment by MrMicky-FR** [comment]
Yes for the admin user created during the installation this is expected to prevent being locked out of the admin panel. Other users are not affected
