### ISSUE TITLE
Bug avec l'authentification (minecraft crack)

### ISSUE THREAD

**Issue by iridiumPvpFaction** [Azuriom/Azuriom#436]
### Bug description

Bonjour, je vous report ce bug car il serait susceptible de gêner pas mal de monde. Ce bug consiste en lors de l'enregistrement sur le site azuriom ( pour ma part je n'ai tester que avec l'option minecraft crack) à rajouter une adresse email déjà utiliser et de rajouter +1 +2 +3 à la fin exemple au lieu de example@gmail.com ce sera example+1@gmail.com etc... à la fin de l'adresse email, azuriom le reconnaîtra en tant que nouvelle adresse e-mail mais le mail arrivera quand même dans la boîte mail de l'utilisateur ( c'est à dire example@gmail.com).

### Step to reproduce

Aller sur la page de registration du site (à condition qu'il y en ai une, pour l'instant je n'ai tester que avec l'option minecraft crack). Ensuite utiliser une adresse mail déjà présente sur le site et rajouter +1 +2 +3 etc... azuriom l'identifira comme une nouvelle adresse email ( si l'adresse email initiale est example@gmail.com, l'adresse email a rentre sera example+1@gmail.com), mais au final cela arrivera dans la boîte mail de l'email initial ( example@gmail.com)

### Web server

Nginx

### Database type

MariaDB

### PHP version

8.2

**Comment by MrMicky-FR** [comment]
C’est un comportement normal puisque `example@gmail.com` et `example+1@gmail.com` sont bien deux adresses différentes.

Le fait que dans ce cas GMail fait que les mails de ces deux adresses arrivent au même endroit arrivent au même endroit ne concerne pas Azuriom. Et il y a aussi de nombreux autres services d’aliases (par exemple [SimpleLogin](https://simplelogin.io/fr/)) donc essayer de détecter un alias ne serait pas efficace
