### ISSUE TITLE
[Forum] Image Upload logs.

### ISSUE THREAD

**Issue by MsEDok** [Azuriom/Azuriom#438]
### Description of your suggestion

An upload log when a user upload an image via forum plugin
when a user upload no matter if they use the image or not as long as the upload success it should log

log location is the admin panel -> Other -> Logs

Action message: `arrow-up-circle Forum upload image 'image name'`

### Advantages

This way if someone decide to "spam" upload button it wouldn't fill up the server storage and it would be easier to identify who is uploading those images
- storage is "cheap" but since there no identification of who upload the image it hard to see who is abusing it.
- identify who doing it and we can punish or warn the user to not do it.

**Comment by MrMicky-FR** [comment]
Adding this to the forum suggestions and closing this as it's not the appropriate repo :)
