### ISSUE TITLE
Transfering Azuriom data from one host to other

### ISSUE THREAD

**Issue by Prozoon700** [Azuriom/Azuriom#439]
### Bug description

Hi.
I try to Transfer all my data (files and db) from my localhost web to a host I have, but when I try to enter the web it runs into an error (something didn't load correclty, error 500).
I've tried to clean-install Azuriom and the move the files, except for the .env and works for me (admin) and anonimous, but if you register or login as a non-host user the error 500 is displayed.
I Hope someone can help me and thanks.

### Step to reproduce

Explained in the bug description section.

### Errors / Logs

error 500 (I'll upload it soon).

### Web server

Nginx

### Database type

MariaDB

### PHP version

8.1

### Additional context

Ask me if needed.

**Comment by MrMicky-FR** [comment]
Please send the logs located in `storage/logs` folder

**Comment by Prozoon700** [comment]
Here is the log
[laravel-2024-05-01.log](https://github.com/Azuriom/Azuriom/files/15189906/laravel-2024-05-01.log)

**Comment by MrMicky-FR** [comment]
Seems to be an issue related to your theme, try contacting the theme developer

**Comment by Prozoon700** [comment]
I only have installed the Flauw theme, but the error seems to be about Illuminate, isn't it?

**Comment by MrMicky-FR** [comment]
Can you delete this log file and reproduce the issue after disabling the theme?

**Comment by Prozoon700** [comment]
I cannot enter the website
![image](https://github.com/Azuriom/Azuriom/assets/65341326/469683da-9e0f-4bcf-8dfb-57be3d656624)

**Comment by MrMicky-FR** [comment]
Can you post your issue in the #support channel on our [Discord server](https://azuriom.com/discord), thanks !

**Comment by Prozoon700** [comment]
Okay, ill do
