### ISSUE TITLE
Import data from another Azuriom instance

### ISSUE THREAD

**Issue by Prozoon700** [Azuriom/Azuriom#440]
### Description of your suggestion

Hi.
I have installed Azuriom in two different hosts and I tried have the same config and data, copying the exact same files and sql, but when trying to access the web I obtained the 500 error.

I think this behaviour (importing data) could be very useful to move Azuriom from one host to another.
If its useful I saw this feature in the Nameless webs.

### Advantages

Moving Azuriom from one host to another without any problem or data loss.

**Comment by MrMicky-FR** [comment]
Azuriom can be moved from one host to the other by copying files and database on the new host.

You might need to adjust the database credentials in the `.env` file as indicated in the [FAQ](https://azuriom.com/docs/faq).

**Comment by Prozoon700** [comment]
I have adjust all the database data and the permissions but stills giving 500 error

**Comment by crashzk** [comment]
If you have an 500 error, make sure to send the logs located in the directory `storage/logs`.
