### ISSUE TITLE
Delete attachments when the associated model is deleted

### ISSUE THREAD

**Issue by I2aYZeI2o** [Azuriom/Azuriom#445]
### Description of your suggestion

From what i can see the attachment handling for deleted resources doesn't seem to have been implemented but it was implemented for when a resource get update.
in plugin 
Forum: when uploading an image to a post the one creating the post and when delete the forum post it self the image isn't marked to deletion I the attachments
the same goes for post comment
it only mark as delete when we edit the comment and remove the image.

my suggestion is that have it check on deletion to mark the image to delete and when a forum post get delete also mark it.
the same goes for support module when we delete a ticket it doesn't mark the image for deletion

There a attachmentpurge command which work for pending image and attachment but attachment doesn't get marked to be deleted.

### Advantages

When deleting the post, forum, ticket the image get delete completely instead of them being in the system (there 1 day for deletion) but how it is rightnow if someone were to delete their own forum post those image will be I the system forever.

**Comment by MrMicky-FR** [comment]
Good catch, thank you! It's fixed in Azuriom v1.1.10, tbh I'm even surprised that I totally forgot to delete attachments when the related model (message, post, etc) is deleted 😅 Especially since all other cases where an attachment is no longer needed are meticulously handled.
