### ISSUE TITLE
Configurable avatar service for minecraft

### ISSUE THREAD

**Issue by MsEDok** [Azuriom/Azuriom#446]
### Description of your suggestion

The current avatar service Azuriom uses is "crafatar" and they block discord embed due to traffic spoofing https://github.com/crafatar/crafatar/issues/322

and this make it so that embed link that use player avatar doesn't show up.

These are some of the service that can be use.

crafatar: https://crafatar.com/avatars/{$uuid}?size={$size}&overlay&default=MHF_Steve
crafthead: https://crafthead.net/helm/{$uuid}/{$size}
cravatar: https://cravatar.eu/helmavatar/{$uuid}/{$size}.png
minotar: https://minotar.net/helm/{$uuid}/{$size}.png

### Advantages

Embed show up on discord and if a service is down we can switch to another one that might work instead of a hard coded value.

**Comment by MrMicky-FR** [comment]
The avatar service can be changed here if needed:
https://github.com/Azuriom/Azuriom/blob/ef9755f238b213d48759d86f4ff57d231af5b2cc/app/Games/Minecraft/MinecraftOnlineGame.php#L35

We were using Minotar and CraftHead but users got issues with both services being down before
