### ISSUE TITLE
Error in vendor/laravel/framework/src/Illuminate/Database/Connection.php

### ISSUE THREAD

**Issue by OliverP98** [Azuriom/Azuriom#450]
### Bug description

Good Afternoon,

I was made aware from one of my users trying to create an account on the website that they would get 500 error. They were able to login using their credentials, they went to the account screen and tried to verify their email, it would give a 500 error again and not send the email.

I tried this myself and this was the observed behaviour.

I have looked into the logs and over the last 6 days I have log files of 15.82MB with the same error being thrown once a minute for the whole time.

 I am able to send the full log if required, I have looked into the log and have narrowed it down to the following:

I have just replaced what is in italics to something generic.

I am not sure what could be causing this error.

Thank you for your time, and making a good product.
Oliver

### Step to reproduce

I was made aware from one of my users trying to create an account on the website that they would get 500 error. They were able to login using their credentials, they went to the account screen and tried to verify their email, it would give a 500 error again and not send the email.

I tried this myself and this was the observed behaviour.

### Errors / Logs

 production.ERROR: SQLSTATE[HY000] [2002] No such file or directory (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'sentine3_azuriom' and table_type = 'BASE TABLE' order by table_name) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = '_database_name_' and table_type = 'BASE TABLE' order by table_name) at /home/_hostname_/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:822)

### Web server

Apache

### Database type

MySQL

### PHP version

8.3

### Additional context

I believe this could have come around through an update and/or inclusion of the support plugin after a long period of not using it.

**Comment by MrMicky-FR** [comment]
```
SQLSTATE[HY000] [2002] No such file or directory
```

This issue seems related to your MySQL server, although I’m not sure of the exact cause
