### ISSUE TITLE
An API to use with Discord Bot

### ISSUE THREAD

**Issue by BearlessDev** [Azuriom/Azuriom#455]
### Description of your suggestion

It would be good to have an API to use it in a Discord Bot, it could be used for example to retrieve the information sent by the site from Webhooks and send it to Discord in the way you want.

For example: You have a webhook configured on changelogs and when you post your changelogs you cannot modify the display of the changelogs on your Discord.
This is why it would be good if with an API we could manage the data we receive from the site and send it back as we wish.

**Comment by MrMicky-FR** [comment]
This should be a suggestion for the changelog plugin
