### ISSUE TITLE
2FA verify

### ISSUE THREAD

**Issue by kolya112** [Azuriom/Azuriom#461]
### Bug description

Hello, what should I do if the codes from the temporary code generation application do not work (I used Google Authenticator and Microsoft Authenticator), an error about the incorrectly entered code appears? I tried to register a new account, the situation repeated. I added both via QR code and via secret key. The backup codes that were issued when connecting 2FA work.

### Step to reproduce

Verify 2FA auth

### Web server

Apache

### Database type

MySQL

**Comment by MrMicky-FR** [comment]
Make sure the time (and timezone) of your server is correct, as TOTP 2FA is based on current time to generate/validate the code

**Comment by kolya112** [comment]
Thanks!
