### ISSUE TITLE
Jeu qui s'active pas en Custom Game

### ISSUE THREAD

**Issue by hanaemercier** [Azuriom/Azuriom#462]
### Bug description

Lorsqu'on fait un jeu custom en local en exécutant php artisan game:create "nom du jeu" et qu'on l'active ça fonctionne. Mais lorsqu'on met le jeu fait en local dans un site différent de là ou la commande a été exécutée et qu'on l'active ça ne détecte pas le jeu et reste en "None".

![image](https://github.com/user-attachments/assets/73c1e9cb-8eef-449d-a94a-65f07d627f4d)

### Step to reproduce

Faire un jeu custom, le mettre dans un autre site, l'activer

### Web server

Apache

### Database type

MySQL

### PHP version

8.2

**Comment by MrMicky-FR** [comment]
Le jeu doit être défini dans le fichier `.env`, à la ligne `AZURIOM_GAME`
