### ISSUE TITLE
Add premium and non-premium minecraft accounts at the same time

### ISSUE THREAD

**Issue by Riptiaz** [Azuriom/Azuriom#466]
### Description of your suggestion

Quick question: do you think that for a future version you could implement the option of connecting via Microsoft (premium) AND also by creating an account on the site, because currently we have to choose between the two and it's a shame.
You'd also have to add in the auth api whether the account is premium or not!
Thanks a lot!

**Comment by MrMicky-FR** [comment]
This is because you have to choose on the server: if you are using an auth plugin like AuthMe, all players would have to register/login. Otherwise on a online mode server, all players must use a Microsoft account to login

**Comment by Riptiaz** [comment]
plugins exist that automatically connect people who are connected with a premium account, and ask for codes to connect for others
https://www.spigotmc.org/resources/fastlogin.14153/
