### ISSUE TITLE
More

### ISSUE THREAD

**Issue by KalviPL** [Azuriom/Azuriom#468]
### Description of your suggestion

More games in the server types without selecting a game at the beginning of the installation>

If any server network wants to make a site for different games they have to have several Azuriom sites because you can't add more games like Minecraft when you choose Rust at the beginning of the installation

![image](https://github.com/user-attachments/assets/cc9ac6b4-1684-48a0-b2ba-0436cf238cd3)

### Advantages

If any server network wants to make a site for different games they have to have several Azuriom sites because you can't add more games like Minecraft when you choose Rust at the beginning of the installation

**Comment by MrMicky-FR** [comment]
This would require basically major changes in the structure, because for example if you have a Minecraft installation and want to connect a Rust server, how the website could know the SteamID if the user logged in with Microsoft and not Steam?

**Comment by KalviPL** [comment]
> This would require basically major changes in the structure, because for example if you have a Minecraft installation and want to connect a Rust server, how the website could know the SteamID if the user logged in with Microsoft and not Steam?

You can make one account and then you link accounts e.g. Steam / Discord / Microsoft etc.

**Comment by MrMicky-FR** [comment]
It would still require major changes as all related plugins would need to be adapted to support this system

**Comment by KalviPL** [comment]
> It would still require major changes as all related plugins would need to be adapted to support this system

It's a shame because having several pages for different games doesn't make sense

**Comment by MrMicky-FR** [comment]
Azuriom is open-source, feel free to contribute in this case :)
