### ISSUE TITLE
Envoie mail de vérification d'adresse mail ne fonctionne pas

### ISSUE THREAD

**Issue by poskio** [Azuriom/Azuriom#473]
### Bug description

Bonjour, lorsqu'un utilisateur clique sur le bouton pour la vérification de l'email, ça ne l'envoie pas ( même dans les spam ) 
En revanche l'envoie du mail de test fonctionne bien, je le reçoie
![image-15](https://github.com/user-attachments/assets/0d2119cd-58db-49e5-a216-82ad01560fde)

avec sendmail même résultat...

### Step to reproduce

Profile -> Cliquer sur le bouton "Renvoyer"

### Database type

MySQL

### PHP version

8.0.2

### Additional context

j'ai remarqué que si un utilisateur fais la demande de reset de mot de passe avec l'email, l'utilisateur reçoie bel et bien le mail. Donc seulement la vérification de l'email semble de ne pas fonctionner

**Comment by MrMicky-FR** [comment]
Testé de mon côté et ca fonctionne, et pas assez d'informations pour tracer le problème 😕

**Comment by poskio** [comment]
J'ai aucune erreur dans les logs, 
Il faudrait quoi comme information pour permettre de tracer le problème ?
