### ISSUE TITLE
1.2.2 breaked database setup settings on register/boot step

### ISSUE THREAD

**Issue by Elikill58** [Azuriom/Azuriom#474]
### Bug description

I was using this:
```php
public function boot() {
   $this->changeDatabase();
}

public function changeDatabase() {
    $dbType = config("database.default");
    config([
        'database.connections.positivity.driver' => 'mysql',
        'database.connections.positivity.host' => setting('positivity.host') ?? config("database.connections." . $dbType . ".host"),
        'database.connections.positivity.port' => setting('positivity.port') ?? config("database.connections." . $dbType . ".port"),
        'database.connections.positivity.username' => setting('positivity.username') ?? config("database.connections." . $dbType . ".username"),
        'database.connections.positivity.password' => setting('positivity.password') ?? config("database.connections." . $dbType . ".password"),
        'database.connections.positivity.database' => setting('positivity.database') ?? config("database.connections." . $dbType . ".database")
    ]);
}
```
Since the latest version (1.2.2), this no longer works as the database `positivity` doesn't seems to be available.

### Step to reproduce

```php
public function boot() {
   $this->changeDatabase();
}

public function changeDatabase() {
    $dbType = config("database.default");
    config([
        'database.connections.positivity.driver' => 'mysql',
        'database.connections.positivity.host' => setting('positivity.host') ?? config("database.connections." . $dbType . ".host"),
        'database.connections.positivity.port' => setting('positivity.port') ?? config("database.connections." . $dbType . ".port"),
        'database.connections.positivity.username' => setting('positivity.username') ?? config("database.connections." . $dbType . ".username"),
        'database.connections.positivity.password' => setting('positivity.password') ?? config("database.connections." . $dbType . ".password"),
        'database.connections.positivity.database' => setting('positivity.database') ?? config("database.connections." . $dbType . ".database")
    ]);
}
```
And then `MyObject::on("positivity")->get()`.

### Web server

Apache

### Database type

MariaDB

### PHP version

8.3

**Comment by MrMicky-FR** [comment]
« Doesn’t work » give exactly 0 useful information on the issue.

Also plugin-specific logic should be avoided in the providers, as they are invoked for all requests on the website, instead it should be only in the plugin controllers

**Comment by Elikill58** [comment]
That's my objective to make it on all pages. It's a common behavior of all controllers. So instead of copying code, I was simply declaring it one time and that's all.

I doesn't works because the database declared in the provider is not available somewhere else. It's using default connection instead of my own one.

**Comment by MrMicky-FR** [comment]
By all pages, I mean **all** pages of the website, even the ones not related to the plugin. This connection is definitely not going to be used on the home page of the website, the shop, support or the admin dashboard for example.

If there is multiple controllers, using a trait or an abstract class might be a solution to avoid duplicated code
