### ISSUE TITLE
Can't auto install on cPanel

### ISSUE THREAD

**Issue by HamDerPedersen** [Azuriom/Azuriom#476]
### Bug description

Hi,
I encountered an error while attempting to install Azuriom on my cPanel server. I have already checked for missing extensions in cPanel and confirmed that all the required extensions are installed.
I also tried installing version 1.2.2, but I encountered the same error with that version as well.

![image](https://github.com/user-attachments/assets/d7ffb31a-2f27-4e6b-bb0a-c6f3a5136040)

### Step to reproduce

.

### Errors / Logs

![image](https://github.com/user-attachments/assets/0e42b71f-1070-40ec-9adf-c0538e36a314)

### Web server

Apache

### Database type

None

### PHP version

8.2.25

**Comment by MrMicky-FR** [comment]
Hello, seems like the database cannot be created, could you try deleting the `.env` file (and NOT `.env.example`) and restart installation ? Also I would recommend MySQL (or PostrgreSQL) instead of SQLite
