### ISSUE TITLE
Ajouter la possibilité de mettre une image qui vient d'une url externe

### ISSUE THREAD

**Issue by Shykaruu** [Azuriom/Azuriom#478]
### Description of your suggestion

Ajouter la possibilité de créer une image dans la section images du panel admin qui vient d'une autre url et sans forcement l'ajouter au storage du site.

### Advantages

Permet de soulager la charge du site si jamais il y a trop de requète vers des images qui serait donc charger depuis un autre serveur/url.

**Comment by MrMicky-FR** [comment]
> Permet de soulager la charge du site si jamais il y a trop de requète vers des images qui serait donc charger depuis un autre serveur/url.

C'est le rôle d'un CDN comme Cloudflare ou Bunny.net, surtout que les images sont statiques donc utilisent que de la bande passante, et là l'idée c'est d'optimiser les images (compression et idéalement format SVG) et configurer le serveur web (Apache ou Nginx) pour que les images soient mises en cache.

Globalement mettre des images externes est une mauvaise pratique, et c'est comme ça qu'on se retrouve sans raisons avec des tonnes de sites qui hébergent leurs images sur Discord, ce qui est un nid à 404
