### ISSUE TITLE
Erreur 500

### ISSUE THREAD

**Issue by EduardoSP85** [Azuriom/Azuriom#479]
### Bug description

![image](https://github.com/user-attachments/assets/a1b92386-dd53-4ac8-b5de-dc068ee4ede1)

Bonjour lorsque mes joueurs et moi essayons de nous connecter sur le site de la communauté hébergé chez vous
j'ai une erreur interne 500

Le Site:  https://crazyland.azuriom.cloud

### Step to reproduce

L'erreur se produit lorsque quelqu'un essaye de se connecter ou de s'inscrire sur le site https://crazyland.azuriom.cloud

Je l'héberge directement chez vous, donc le problème devrait provenir de vos serveurs.

### Web server

Other

### Database type

None

**Comment by MrMicky-FR** [comment]
This is more related to the Azuriom installation itself (in this case AzuriomCloud) than Azuriom
