### ISSUE TITLE
Admin panel bug

### ISSUE THREAD

**Issue by Oximov** [Azuriom/Azuriom#58]
In the main page of the admin panel, the number of users is not equal to the number of users recorded in the table of the dedicated page
![OXI](https://user-images.githubusercontent.com/53126647/108103503-52b01000-708a-11eb-83f1-afcdba8b19f8.png)
![OXI2](https://user-images.githubusercontent.com/53126647/108103507-53e13d00-708a-11eb-9e58-cd318ba09d23.png)

**Comment by ZeProf2Code** [comment]
Is one of your users soft deleted?
