### ISSUE TITLE
Faute de frappe

### ISSUE THREAD

**Issue by LouissXI** [Azuriom/Azuriom#63]
Bonjour, 

Lorsqu'on supprime un plugin, cela nous affiche ce message : 
![image](https://user-images.githubusercontent.com/56359155/113516347-09ece180-957a-11eb-90cd-3792de1434f4.png)
Mais au mieux de nous écrire "Le plugin a été supprimé.", ça nous écrit "Le plus a été supprimé."

Cette erreur n'est pas importante mais elle a quand même son importance x).

Cordialement, Louis

**Comment by MrMicky-FR** [comment]
Merci, effectivement la phrase comme ça n'a pas trop de sens x) Ça sera corrigé dans la prochaine mise à jour :)

**Comment by Mimexe** [comment]
Maintenant je comprend la mise a jour 0.3.7

**Comment by MrMicky-FR** [comment]
> Maintenant je comprend la mise a jour 0.3.7

Il n’y a pas que ça qui a été modifié dans la mise à jour 0.3.7 (heureusement d’ailleurs) : https://github.com/Azuriom/Azuriom/releases/tag/v0.3.7 👀
