### ISSUE TITLE
Support for custom games

### ISSUE THREAD

**Issue by jwoff78** [Azuriom/Azuriom#64]
I can probably navigate the source and add support for a custom game, the game isn't currently on the market, it's one I am developing. Is there a good way to go about adding custom support? (this game has private servers)

**Comment by MrMicky-FR** [comment]
Hi,
You can make a plugin that calls `GameServiceProvider::registerGames(['your-game'=> YourGame::class]);` where `YourGame` is a class that extends the class `Game`. For a full example you can take a look at https://github.com/AzuriomCommunity/Game-Flyff

The installation process will be improved soon so custom games can be added easily

**Comment by MrMicky-FR** [comment]
Added in #80
