### ISSUE TITLE
Add additional user arguments {steamid} & {steamid64} with the {player} option.

### ISSUE THREAD

**Issue by thewhistledev** [Azuriom/Azuriom#72]
Add {steamid} {steamid64} support for games like garry's mod for addons that need steam id / 64 id to work, for the store addon.

**Comment by MrMicky-FR** [comment]
You can already use:
- `{steam_id}` for the **SteamID 64** of the player (eg `76561198048368658`) 
- `{steam_id_32}` for the **SteamID 32** of the player (eg `STEAM_0:0:44051465`)

**Comment by MrMicky-FR** [comment]
These placeholders are now displayed below the commands field
