### ISSUE TITLE
Fix role hierarchy.

### ISSUE THREAD

**Issue by Fabian-Evolved** [Azuriom/Azuriom#77]
Currently its possible for staff roles to demote a staff that is listed higher then them in the hierarchy, however they can not add roles that are listed higher than them. But they are able to demote someone listed higher in the role hierarchy.

I hope this made sense.

So basically i have the following hierarchy.

1. Management
2. Staff
3. Moderator

So in this example people that have the Staff role, are able to change the management members role to staff, effectively demoting them to staff permissions, even though staff does not have full admin privileges. They are however not able to upgrade for example a moderator to management, because management is listed higher than them.

I hope i made the example clear enough, if you have any questions, or don't understand what i mean, please let me know.

**Comment by Javdu10** [comment]
This should be fixed with #480f228
However there are no version bump yet

**Comment by MrMicky-FR** [comment]
Fixed in the latest version
