### ISSUE TITLE
Ajout de serveur impossible `fwrite() […] Operation not permitted`

### ISSUE THREAD

**Issue by AlzheTV** [Azuriom/Azuriom#78]
Bonjour messieurs.

J'ai un léger soucis, je ne peux pas ajouter mon serveur Garry's Mod pour l'instant, car ce message d'erreur sort : `La connexion au serveur a échouée: fwrite(): send of 25 bytes failed with errno=1 Operation not permitted`.

Je viens ici pour demander de l'aide, je voudrais aussi savoir où ce situes les logs du site pour voir où je peux voir ça et si ça viendrait pas de mon hébergeur.

## Screenshot de l'erreur :
![image](https://user-images.githubusercontent.com/68754021/127055756-a45ddd12-7cff-4f2e-becd-7f95a5388a26.png)

Amicalement,
alzhetv.

**Comment by SyFizz** [comment]
Bonsoir,

Premièrement, le support pour les problèmes liés à l'utilisateur et non à un bug dans le CMS doit normalement s'effectuer sur le serveur Discord (https://discord.gg/VKpSJrV )
Les logs du site se situent dans le dossier /storage/logs.

Cordialement,
Grégory B.

**Comment by Javdu10** [comment]
EN:

Hello @AlzheTV, `Operation not permitted` means that your hosting provider desactivated the function, you have two solutions.

1. Ask the support of your hosting provider to enable the function
2. Change your provider

FR: 

Bonjour @AlzheTV, `Operation not permitted` signifie que votre hébergeur a désactivé la fonction, vous avez deux solutions.

1. Demander au support de votre fournisseur d'hébergement d'activer la fonction
2. Changer d'hébergeur
