### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Justman10000** [Azuriom/Azuriom#82]
I'm working on translating Azuriom to German but can't upload files or folders! Since you can only create files, I could not upload this language pack!

**Comment by Justman10000** [comment]
Same with the plugins!

**Comment by Fabian-Evolved** [comment]
> I'm working on translating Azuriom to German but can't upload files or folders! Since you can only create files, I could not upload this language pack!

Use their Crowdin page: https://translate.azuriom.com/
Create a Crowdin account, and you will able to start applying translations for German language. They will have to be upvoted and approved though.

**Comment by Justman10000** [comment]
> 
> 
> > I'm working on translating Azuriom to German but can't upload files or folders! Since you can only create files, I could not upload this language pack!
> 
> Use their Crowdin page: https://translate.azuriom.com/
> Create a Crowdin account, and you will able to start applying translations for German language. They will have to be upvoted and approved though.

German has already been fully added! Except for English and French, there are no other languages ​​to choose from!

**Comment by MrMicky-FR** [comment]
Hi, we will implement complete Crowdin translations soon :)

**Comment by Justman10000** [comment]
@MrMicky-FR 

Hello?

**Comment by MrMicky-FR** [comment]
Hi, I am pretty busy and I don’t have access to my computer currently, so I don’t have any ETA

**Comment by Justman10000** [comment]
Well, I could publish it, it would be nice 🤩!

**Comment by MrMicky-FR** [comment]
Hi, after way too much time we finally found a solution for the translations :)

Now all completed translations (including for extensions) will be directly included in Azuriom releases with the latest Crowdin version (for reference: 5b04ec66284638a93781f6959e167d40c223ee02 & 0bc54f6dc5f84bc0c88dcc3f0d4543e4e21b354e).

The next Azuriom release should be published in few days.
