### ISSUE TITLE
Plugin loading shouldn't block the whole application if an exception occurred

### ISSUE THREAD

**Issue by magrigry** [Azuriom/Azuriom#90]
If an exception is thrown while a plugin is loading the whole application crash.  

It may happen for example while registering a plugin's service provider because of Azuriom not up to date but and plugin written for latest Azuriom version
An exception at this step will block the whole application and user won't be able to remove the plugin from the panel 

Imho those exceptions should be handled for loging and plugin loading should be cancelled

**Comment by MrMicky-FR** [comment]
We solved this on Discord, closing this as AFAIK there is no easy way to catch this with Laravel :/
