### ISSUE TITLE
Thème Oasis, 2FA

### ISSUE THREAD

**Issue by Doncellup3** [Azuriom/Azuriom#94]
Bonjour, je voudrais signaler qu'il est impossible de scanner le QR code de la 2FA avec le thème Oasis car le fond de la page est noir. Il faudrait un contour blanc pour rendre le QR code visible

![image](https://user-images.githubusercontent.com/90469321/132885214-f56ea78d-3ae4-4147-b730-511e1c807bd1.png)

**Comment by MrMicky-FR** [comment]
Bonjour, il faudrait signaler ce problème directement à l’auteur du thème car nous ne pouvons rien faire pour les thèmes qui ne sont pas sur GitHub.
