### ISSUE TITLE
Error 405 with Cloudflare's under attack mode

### ISSUE THREAD

**Issue by ElBananaa** [Azuriom/Azuriom#98]
I recently noticed I am getting an error 405 after the browser check with the under attack mode.
All my plugins are up to date, as same as the cms, and the cloudflare plugin is installed.

I first thought this was related to the latest version since I don't remember having this issue on previous versions, but according to MrMicky this was already here before ^^

**Comment by DuckyDou** [comment]
Same here

**Comment by MrMicky-FR** [comment]
Seems like Cloudflare updated Under Attack mode and this issue is no longer present :)
