### ISSUE TITLE
Link player account

### ISSUE THREAD

**Issue by Cr4zyGeek** [Azuriom/Azuriom#99]
At the moment of the registration or later, add the optional possibility to link the website account to the Minecraft account to be sure the account created on the website is owned by the player who own the same username in-game.

Maybe it could be also interesting to set the website username by the user's Minecraft account username when linked, which means we could create a website account with a username different than our Minecraft account, and when we are linked the displayed website username will be the Minecraft account username.

**Comment by MrMicky-FR** [comment]
Improving ingame and website accounts linking is planned, for online-mode servers it will be by using the OAuth connection through Microsoft when the migration from Mojang accounts to Microsoft accounts is done.

**Comment by Cr4zyGeek** [comment]
Thanks for your fast reply,
do you plan a solution for servers accepting players with a non-premium account ?

**Comment by MrMicky-FR** [comment]
Yes, I think adding a `/link` in-game command and/or an AuthMe integration would a be a good option

**Comment by DuckyDou** [comment]
Jpremium support
